/* Automatically generated by mkcoglconsts.rb */

/* Ruby bindings for the Clutter 'interactive canvas' library.
 * Copyright (C) 2007-2008  Neil Roberts
 * 
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 * 
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA  02110-1301  USA
 */

#include <rbgobject.h>
#include <cogl/cogl.h>

#include "rbclutter.h"

void
rb_cogl_consts_init (void)
{
  VALUE enum_module;

  enum_module = rb_define_module_under (rbclt_c_cogl, "PixelFormat");
  rb_define_const (enum_module, "ANY",
                   INT2FIX (COGL_PIXEL_FORMAT_ANY));
  rb_define_const (enum_module, "A_8",
                   INT2FIX (COGL_PIXEL_FORMAT_A_8));
  rb_define_const (enum_module, "RGB_565",
                   INT2FIX (COGL_PIXEL_FORMAT_RGB_565));
  rb_define_const (enum_module, "RGBA_4444",
                   INT2FIX (COGL_PIXEL_FORMAT_RGBA_4444));
  rb_define_const (enum_module, "RGBA_5551",
                   INT2FIX (COGL_PIXEL_FORMAT_RGBA_5551));
  rb_define_const (enum_module, "YUV",
                   INT2FIX (COGL_PIXEL_FORMAT_YUV));
  rb_define_const (enum_module, "G_8",
                   INT2FIX (COGL_PIXEL_FORMAT_G_8));
  rb_define_const (enum_module, "RGB_888",
                   INT2FIX (COGL_PIXEL_FORMAT_RGB_888));
  rb_define_const (enum_module, "BGR_888",
                   INT2FIX (COGL_PIXEL_FORMAT_BGR_888));
  rb_define_const (enum_module, "RGBA_8888",
                   INT2FIX (COGL_PIXEL_FORMAT_RGBA_8888));
  rb_define_const (enum_module, "BGRA_8888",
                   INT2FIX (COGL_PIXEL_FORMAT_BGRA_8888));
  rb_define_const (enum_module, "ARGB_8888",
                   INT2FIX (COGL_PIXEL_FORMAT_ARGB_8888));
  rb_define_const (enum_module, "ABGR_8888",
                   INT2FIX (COGL_PIXEL_FORMAT_ABGR_8888));
  rb_define_const (enum_module, "RGBA_8888_PRE",
                   INT2FIX (COGL_PIXEL_FORMAT_RGBA_8888_PRE));
  rb_define_const (enum_module, "BGRA_8888_PRE",
                   INT2FIX (COGL_PIXEL_FORMAT_BGRA_8888_PRE));
  rb_define_const (enum_module, "ARGB_8888_PRE",
                   INT2FIX (COGL_PIXEL_FORMAT_ARGB_8888_PRE));
  rb_define_const (enum_module, "ABGR_8888_PRE",
                   INT2FIX (COGL_PIXEL_FORMAT_ABGR_8888_PRE));
  rb_define_const (enum_module, "RGBA_4444_PRE",
                   INT2FIX (COGL_PIXEL_FORMAT_RGBA_4444_PRE));
  rb_define_const (enum_module, "RGBA_5551_PRE",
                   INT2FIX (COGL_PIXEL_FORMAT_RGBA_5551_PRE));
  enum_module = rb_define_module_under (rbclt_c_cogl, "FeatureFlags");
  rb_define_const (enum_module, "TEXTURE_RECTANGLE",
                   INT2FIX (COGL_FEATURE_TEXTURE_RECTANGLE));
  rb_define_const (enum_module, "TEXTURE_NPOT",
                   INT2FIX (COGL_FEATURE_TEXTURE_NPOT));
  rb_define_const (enum_module, "TEXTURE_YUV",
                   INT2FIX (COGL_FEATURE_TEXTURE_YUV));
  rb_define_const (enum_module, "TEXTURE_READ_PIXELS",
                   INT2FIX (COGL_FEATURE_TEXTURE_READ_PIXELS));
  rb_define_const (enum_module, "SHADERS_GLSL",
                   INT2FIX (COGL_FEATURE_SHADERS_GLSL));
  rb_define_const (enum_module, "OFFSCREEN",
                   INT2FIX (COGL_FEATURE_OFFSCREEN));
  rb_define_const (enum_module, "OFFSCREEN_MULTISAMPLE",
                   INT2FIX (COGL_FEATURE_OFFSCREEN_MULTISAMPLE));
  rb_define_const (enum_module, "OFFSCREEN_BLIT",
                   INT2FIX (COGL_FEATURE_OFFSCREEN_BLIT));
  rb_define_const (enum_module, "FOUR_CLIP_PLANES",
                   INT2FIX (COGL_FEATURE_FOUR_CLIP_PLANES));
  rb_define_const (enum_module, "STENCIL_BUFFER",
                   INT2FIX (COGL_FEATURE_STENCIL_BUFFER));
  enum_module = rb_define_module_under (rbclt_c_cogl, "BufferTarget");
  rb_define_const (enum_module, "WINDOW_BUFFER",
                   INT2FIX (COGL_WINDOW_BUFFER));
  rb_define_const (enum_module, "MASK_BUFFER",
                   INT2FIX (COGL_MASK_BUFFER));
  rb_define_const (enum_module, "OFFSCREEN_BUFFER",
                   INT2FIX (COGL_OFFSCREEN_BUFFER));
#ifdef GL_ACCUM
  rb_define_const (rbclt_c_cogl, "ACCUM",
                   INT2FIX (CGL_ACCUM));
#endif
#ifdef GL_ACCUM_ALPHA_BITS
  rb_define_const (rbclt_c_cogl, "ACCUM_ALPHA_BITS",
                   INT2FIX (CGL_ACCUM_ALPHA_BITS));
#endif
#ifdef GL_ACCUM_BLUE_BITS
  rb_define_const (rbclt_c_cogl, "ACCUM_BLUE_BITS",
                   INT2FIX (CGL_ACCUM_BLUE_BITS));
#endif
#ifdef GL_ACCUM_BUFFER_BIT
  rb_define_const (rbclt_c_cogl, "ACCUM_BUFFER_BIT",
                   INT2FIX (CGL_ACCUM_BUFFER_BIT));
#endif
#ifdef GL_ACCUM_CLEAR_VALUE
  rb_define_const (rbclt_c_cogl, "ACCUM_CLEAR_VALUE",
                   INT2FIX (CGL_ACCUM_CLEAR_VALUE));
#endif
#ifdef GL_ACCUM_GREEN_BITS
  rb_define_const (rbclt_c_cogl, "ACCUM_GREEN_BITS",
                   INT2FIX (CGL_ACCUM_GREEN_BITS));
#endif
#ifdef GL_ACCUM_RED_BITS
  rb_define_const (rbclt_c_cogl, "ACCUM_RED_BITS",
                   INT2FIX (CGL_ACCUM_RED_BITS));
#endif
#ifdef GL_ACTIVE_TEXTURE
  rb_define_const (rbclt_c_cogl, "ACTIVE_TEXTURE",
                   INT2FIX (CGL_ACTIVE_TEXTURE));
#endif
#ifdef GL_ACTIVE_TEXTURE_ARB
  rb_define_const (rbclt_c_cogl, "ACTIVE_TEXTURE_ARB",
                   INT2FIX (CGL_ACTIVE_TEXTURE_ARB));
#endif
#ifdef GL_ADD
  rb_define_const (rbclt_c_cogl, "ADD",
                   INT2FIX (CGL_ADD));
#endif
#ifdef GL_ADD_SIGNED
  rb_define_const (rbclt_c_cogl, "ADD_SIGNED",
                   INT2FIX (CGL_ADD_SIGNED));
#endif
#ifdef GL_ALIASED_LINE_WIDTH_RANGE
  rb_define_const (rbclt_c_cogl, "ALIASED_LINE_WIDTH_RANGE",
                   INT2FIX (CGL_ALIASED_LINE_WIDTH_RANGE));
#endif
#ifdef GL_ALIASED_POINT_SIZE_RANGE
  rb_define_const (rbclt_c_cogl, "ALIASED_POINT_SIZE_RANGE",
                   INT2FIX (CGL_ALIASED_POINT_SIZE_RANGE));
#endif
#ifdef GL_ALL_ATTRIB_BITS
  rb_define_const (rbclt_c_cogl, "ALL_ATTRIB_BITS",
                   INT2FIX (CGL_ALL_ATTRIB_BITS));
#endif
#ifdef GL_ALL_CLIENT_ATTRIB_BITS
  rb_define_const (rbclt_c_cogl, "ALL_CLIENT_ATTRIB_BITS",
                   INT2FIX (CGL_ALL_CLIENT_ATTRIB_BITS));
#endif
#ifdef GL_ALPHA
  rb_define_const (rbclt_c_cogl, "ALPHA",
                   INT2FIX (CGL_ALPHA));
#endif
#ifdef GL_ALPHA_BIAS
  rb_define_const (rbclt_c_cogl, "ALPHA_BIAS",
                   INT2FIX (CGL_ALPHA_BIAS));
#endif
#ifdef GL_ALPHA_BITS
  rb_define_const (rbclt_c_cogl, "ALPHA_BITS",
                   INT2FIX (CGL_ALPHA_BITS));
#endif
#ifdef GL_ALPHA_BLEND_EQUATION_ATI
  rb_define_const (rbclt_c_cogl, "ALPHA_BLEND_EQUATION_ATI",
                   INT2FIX (CGL_ALPHA_BLEND_EQUATION_ATI));
#endif
#ifdef GL_ALPHA_SCALE
  rb_define_const (rbclt_c_cogl, "ALPHA_SCALE",
                   INT2FIX (CGL_ALPHA_SCALE));
#endif
#ifdef GL_ALPHA_TEST
  rb_define_const (rbclt_c_cogl, "ALPHA_TEST",
                   INT2FIX (CGL_ALPHA_TEST));
#endif
#ifdef GL_ALPHA_TEST_FUNC
  rb_define_const (rbclt_c_cogl, "ALPHA_TEST_FUNC",
                   INT2FIX (CGL_ALPHA_TEST_FUNC));
#endif
#ifdef GL_ALPHA_TEST_REF
  rb_define_const (rbclt_c_cogl, "ALPHA_TEST_REF",
                   INT2FIX (CGL_ALPHA_TEST_REF));
#endif
#ifdef GL_ALWAYS
  rb_define_const (rbclt_c_cogl, "ALWAYS",
                   INT2FIX (CGL_ALWAYS));
#endif
#ifdef GL_AMBIENT
  rb_define_const (rbclt_c_cogl, "AMBIENT",
                   INT2FIX (CGL_AMBIENT));
#endif
#ifdef GL_AMBIENT_AND_DIFFUSE
  rb_define_const (rbclt_c_cogl, "AMBIENT_AND_DIFFUSE",
                   INT2FIX (CGL_AMBIENT_AND_DIFFUSE));
#endif
#ifdef GL_AND
  rb_define_const (rbclt_c_cogl, "AND",
                   INT2FIX (CGL_AND));
#endif
#ifdef GL_AND_INVERTED
  rb_define_const (rbclt_c_cogl, "AND_INVERTED",
                   INT2FIX (CGL_AND_INVERTED));
#endif
#ifdef GL_AND_REVERSE
  rb_define_const (rbclt_c_cogl, "AND_REVERSE",
                   INT2FIX (CGL_AND_REVERSE));
#endif
#ifdef GL_ARGB
  rb_define_const (rbclt_c_cogl, "ARGB",
                   INT2FIX (CGL_ARGB));
#endif
#ifdef GL_ATTRIB_STACK_DEPTH
  rb_define_const (rbclt_c_cogl, "ATTRIB_STACK_DEPTH",
                   INT2FIX (CGL_ATTRIB_STACK_DEPTH));
#endif
#ifdef GL_AUTO_NORMAL
  rb_define_const (rbclt_c_cogl, "AUTO_NORMAL",
                   INT2FIX (CGL_AUTO_NORMAL));
#endif
#ifdef GL_AUX_BUFFERS
  rb_define_const (rbclt_c_cogl, "AUX_BUFFERS",
                   INT2FIX (CGL_AUX_BUFFERS));
#endif
#ifdef GL_BACK
  rb_define_const (rbclt_c_cogl, "BACK",
                   INT2FIX (CGL_BACK));
#endif
#ifdef GL_BACK_LEFT
  rb_define_const (rbclt_c_cogl, "BACK_LEFT",
                   INT2FIX (CGL_BACK_LEFT));
#endif
#ifdef GL_BACK_RIGHT
  rb_define_const (rbclt_c_cogl, "BACK_RIGHT",
                   INT2FIX (CGL_BACK_RIGHT));
#endif
#ifdef GL_BGR
  rb_define_const (rbclt_c_cogl, "BGR",
                   INT2FIX (CGL_BGR));
#endif
#ifdef GL_BGRA
  rb_define_const (rbclt_c_cogl, "BGRA",
                   INT2FIX (CGL_BGRA));
#endif
#ifdef GL_BITMAP
  rb_define_const (rbclt_c_cogl, "BITMAP",
                   INT2FIX (CGL_BITMAP));
#endif
#ifdef GL_BITMAP_TOKEN
  rb_define_const (rbclt_c_cogl, "BITMAP_TOKEN",
                   INT2FIX (CGL_BITMAP_TOKEN));
#endif
#ifdef GL_BLEND
  rb_define_const (rbclt_c_cogl, "BLEND",
                   INT2FIX (CGL_BLEND));
#endif
#ifdef GL_BLEND_COLOR
  rb_define_const (rbclt_c_cogl, "BLEND_COLOR",
                   INT2FIX (CGL_BLEND_COLOR));
#endif
#ifdef GL_BLEND_DST
  rb_define_const (rbclt_c_cogl, "BLEND_DST",
                   INT2FIX (CGL_BLEND_DST));
#endif
#ifdef GL_BLEND_EQUATION
  rb_define_const (rbclt_c_cogl, "BLEND_EQUATION",
                   INT2FIX (CGL_BLEND_EQUATION));
#endif
#ifdef GL_BLEND_SRC
  rb_define_const (rbclt_c_cogl, "BLEND_SRC",
                   INT2FIX (CGL_BLEND_SRC));
#endif
#ifdef GL_BLUE
  rb_define_const (rbclt_c_cogl, "BLUE",
                   INT2FIX (CGL_BLUE));
#endif
#ifdef GL_BLUE_BIAS
  rb_define_const (rbclt_c_cogl, "BLUE_BIAS",
                   INT2FIX (CGL_BLUE_BIAS));
#endif
#ifdef GL_BLUE_BITS
  rb_define_const (rbclt_c_cogl, "BLUE_BITS",
                   INT2FIX (CGL_BLUE_BITS));
#endif
#ifdef GL_BLUE_SCALE
  rb_define_const (rbclt_c_cogl, "BLUE_SCALE",
                   INT2FIX (CGL_BLUE_SCALE));
#endif
#ifdef GL_BYTE
  rb_define_const (rbclt_c_cogl, "BYTE",
                   INT2FIX (CGL_BYTE));
#endif
#ifdef GL_CCW
  rb_define_const (rbclt_c_cogl, "CCW",
                   INT2FIX (CGL_CCW));
#endif
#ifdef GL_CLAMP
  rb_define_const (rbclt_c_cogl, "CLAMP",
                   INT2FIX (CGL_CLAMP));
#endif
#ifdef GL_CLAMP_TO_BORDER
  rb_define_const (rbclt_c_cogl, "CLAMP_TO_BORDER",
                   INT2FIX (CGL_CLAMP_TO_BORDER));
#endif
#ifdef GL_CLAMP_TO_EDGE
  rb_define_const (rbclt_c_cogl, "CLAMP_TO_EDGE",
                   INT2FIX (CGL_CLAMP_TO_EDGE));
#endif
#ifdef GL_CLEAR
  rb_define_const (rbclt_c_cogl, "CLEAR",
                   INT2FIX (CGL_CLEAR));
#endif
#ifdef GL_CLIENT_ACTIVE_TEXTURE
  rb_define_const (rbclt_c_cogl, "CLIENT_ACTIVE_TEXTURE",
                   INT2FIX (CGL_CLIENT_ACTIVE_TEXTURE));
#endif
#ifdef GL_CLIENT_ACTIVE_TEXTURE_ARB
  rb_define_const (rbclt_c_cogl, "CLIENT_ACTIVE_TEXTURE_ARB",
                   INT2FIX (CGL_CLIENT_ACTIVE_TEXTURE_ARB));
#endif
#ifdef GL_CLIENT_ALL_ATTRIB_BITS
  rb_define_const (rbclt_c_cogl, "CLIENT_ALL_ATTRIB_BITS",
                   INT2FIX (CGL_CLIENT_ALL_ATTRIB_BITS));
#endif
#ifdef GL_CLIENT_ATTRIB_STACK_DEPTH
  rb_define_const (rbclt_c_cogl, "CLIENT_ATTRIB_STACK_DEPTH",
                   INT2FIX (CGL_CLIENT_ATTRIB_STACK_DEPTH));
#endif
#ifdef GL_CLIENT_PIXEL_STORE_BIT
  rb_define_const (rbclt_c_cogl, "CLIENT_PIXEL_STORE_BIT",
                   INT2FIX (CGL_CLIENT_PIXEL_STORE_BIT));
#endif
#ifdef GL_CLIENT_VERTEX_ARRAY_BIT
  rb_define_const (rbclt_c_cogl, "CLIENT_VERTEX_ARRAY_BIT",
                   INT2FIX (CGL_CLIENT_VERTEX_ARRAY_BIT));
#endif
#ifdef GL_COEFF
  rb_define_const (rbclt_c_cogl, "COEFF",
                   INT2FIX (CGL_COEFF));
#endif
#ifdef GL_COLOR
  rb_define_const (rbclt_c_cogl, "COLOR",
                   INT2FIX (CGL_COLOR));
#endif
#ifdef GL_COLOR_ARRAY
  rb_define_const (rbclt_c_cogl, "COLOR_ARRAY",
                   INT2FIX (CGL_COLOR_ARRAY));
#endif
#ifdef GL_COLOR_ARRAY_POINTER
  rb_define_const (rbclt_c_cogl, "COLOR_ARRAY_POINTER",
                   INT2FIX (CGL_COLOR_ARRAY_POINTER));
#endif
#ifdef GL_COLOR_ARRAY_SIZE
  rb_define_const (rbclt_c_cogl, "COLOR_ARRAY_SIZE",
                   INT2FIX (CGL_COLOR_ARRAY_SIZE));
#endif
#ifdef GL_COLOR_ARRAY_STRIDE
  rb_define_const (rbclt_c_cogl, "COLOR_ARRAY_STRIDE",
                   INT2FIX (CGL_COLOR_ARRAY_STRIDE));
#endif
#ifdef GL_COLOR_ARRAY_TYPE
  rb_define_const (rbclt_c_cogl, "COLOR_ARRAY_TYPE",
                   INT2FIX (CGL_COLOR_ARRAY_TYPE));
#endif
#ifdef GL_COLOR_BUFFER_BIT
  rb_define_const (rbclt_c_cogl, "COLOR_BUFFER_BIT",
                   INT2FIX (CGL_COLOR_BUFFER_BIT));
#endif
#ifdef GL_COLOR_CLEAR_VALUE
  rb_define_const (rbclt_c_cogl, "COLOR_CLEAR_VALUE",
                   INT2FIX (CGL_COLOR_CLEAR_VALUE));
#endif
#ifdef GL_COLOR_INDEX
  rb_define_const (rbclt_c_cogl, "COLOR_INDEX",
                   INT2FIX (CGL_COLOR_INDEX));
#endif
#ifdef GL_COLOR_INDEXES
  rb_define_const (rbclt_c_cogl, "COLOR_INDEXES",
                   INT2FIX (CGL_COLOR_INDEXES));
#endif
#ifdef GL_COLOR_LOGIC_OP
  rb_define_const (rbclt_c_cogl, "COLOR_LOGIC_OP",
                   INT2FIX (CGL_COLOR_LOGIC_OP));
#endif
#ifdef GL_COLOR_MATERIAL
  rb_define_const (rbclt_c_cogl, "COLOR_MATERIAL",
                   INT2FIX (CGL_COLOR_MATERIAL));
#endif
#ifdef GL_COLOR_MATERIAL_FACE
  rb_define_const (rbclt_c_cogl, "COLOR_MATERIAL_FACE",
                   INT2FIX (CGL_COLOR_MATERIAL_FACE));
#endif
#ifdef GL_COLOR_MATERIAL_PARAMETER
  rb_define_const (rbclt_c_cogl, "COLOR_MATERIAL_PARAMETER",
                   INT2FIX (CGL_COLOR_MATERIAL_PARAMETER));
#endif
#ifdef GL_COLOR_MATRIX
  rb_define_const (rbclt_c_cogl, "COLOR_MATRIX",
                   INT2FIX (CGL_COLOR_MATRIX));
#endif
#ifdef GL_COLOR_MATRIX_STACK_DEPTH
  rb_define_const (rbclt_c_cogl, "COLOR_MATRIX_STACK_DEPTH",
                   INT2FIX (CGL_COLOR_MATRIX_STACK_DEPTH));
#endif
#ifdef GL_COLOR_TABLE
  rb_define_const (rbclt_c_cogl, "COLOR_TABLE",
                   INT2FIX (CGL_COLOR_TABLE));
#endif
#ifdef GL_COLOR_TABLE_ALPHA_SIZE
  rb_define_const (rbclt_c_cogl, "COLOR_TABLE_ALPHA_SIZE",
                   INT2FIX (CGL_COLOR_TABLE_ALPHA_SIZE));
#endif
#ifdef GL_COLOR_TABLE_BIAS
  rb_define_const (rbclt_c_cogl, "COLOR_TABLE_BIAS",
                   INT2FIX (CGL_COLOR_TABLE_BIAS));
#endif
#ifdef GL_COLOR_TABLE_BLUE_SIZE
  rb_define_const (rbclt_c_cogl, "COLOR_TABLE_BLUE_SIZE",
                   INT2FIX (CGL_COLOR_TABLE_BLUE_SIZE));
#endif
#ifdef GL_COLOR_TABLE_FORMAT
  rb_define_const (rbclt_c_cogl, "COLOR_TABLE_FORMAT",
                   INT2FIX (CGL_COLOR_TABLE_FORMAT));
#endif
#ifdef GL_COLOR_TABLE_GREEN_SIZE
  rb_define_const (rbclt_c_cogl, "COLOR_TABLE_GREEN_SIZE",
                   INT2FIX (CGL_COLOR_TABLE_GREEN_SIZE));
#endif
#ifdef GL_COLOR_TABLE_INTENSITY_SIZE
  rb_define_const (rbclt_c_cogl, "COLOR_TABLE_INTENSITY_SIZE",
                   INT2FIX (CGL_COLOR_TABLE_INTENSITY_SIZE));
#endif
#ifdef GL_COLOR_TABLE_LUMINANCE_SIZE
  rb_define_const (rbclt_c_cogl, "COLOR_TABLE_LUMINANCE_SIZE",
                   INT2FIX (CGL_COLOR_TABLE_LUMINANCE_SIZE));
#endif
#ifdef GL_COLOR_TABLE_RED_SIZE
  rb_define_const (rbclt_c_cogl, "COLOR_TABLE_RED_SIZE",
                   INT2FIX (CGL_COLOR_TABLE_RED_SIZE));
#endif
#ifdef GL_COLOR_TABLE_SCALE
  rb_define_const (rbclt_c_cogl, "COLOR_TABLE_SCALE",
                   INT2FIX (CGL_COLOR_TABLE_SCALE));
#endif
#ifdef GL_COLOR_TABLE_WIDTH
  rb_define_const (rbclt_c_cogl, "COLOR_TABLE_WIDTH",
                   INT2FIX (CGL_COLOR_TABLE_WIDTH));
#endif
#ifdef GL_COLOR_WRITEMASK
  rb_define_const (rbclt_c_cogl, "COLOR_WRITEMASK",
                   INT2FIX (CGL_COLOR_WRITEMASK));
#endif
#ifdef GL_COMBINE
  rb_define_const (rbclt_c_cogl, "COMBINE",
                   INT2FIX (CGL_COMBINE));
#endif
#ifdef GL_COMBINE_ALPHA
  rb_define_const (rbclt_c_cogl, "COMBINE_ALPHA",
                   INT2FIX (CGL_COMBINE_ALPHA));
#endif
#ifdef GL_COMBINE_RGB
  rb_define_const (rbclt_c_cogl, "COMBINE_RGB",
                   INT2FIX (CGL_COMBINE_RGB));
#endif
#ifdef GL_COMPILE
  rb_define_const (rbclt_c_cogl, "COMPILE",
                   INT2FIX (CGL_COMPILE));
#endif
#ifdef GL_COMPILE_AND_EXECUTE
  rb_define_const (rbclt_c_cogl, "COMPILE_AND_EXECUTE",
                   INT2FIX (CGL_COMPILE_AND_EXECUTE));
#endif
#ifdef GL_COMPRESSED_ALPHA
  rb_define_const (rbclt_c_cogl, "COMPRESSED_ALPHA",
                   INT2FIX (CGL_COMPRESSED_ALPHA));
#endif
#ifdef GL_COMPRESSED_INTENSITY
  rb_define_const (rbclt_c_cogl, "COMPRESSED_INTENSITY",
                   INT2FIX (CGL_COMPRESSED_INTENSITY));
#endif
#ifdef GL_COMPRESSED_LUMINANCE
  rb_define_const (rbclt_c_cogl, "COMPRESSED_LUMINANCE",
                   INT2FIX (CGL_COMPRESSED_LUMINANCE));
#endif
#ifdef GL_COMPRESSED_LUMINANCE_ALPHA
  rb_define_const (rbclt_c_cogl, "COMPRESSED_LUMINANCE_ALPHA",
                   INT2FIX (CGL_COMPRESSED_LUMINANCE_ALPHA));
#endif
#ifdef GL_COMPRESSED_RGB
  rb_define_const (rbclt_c_cogl, "COMPRESSED_RGB",
                   INT2FIX (CGL_COMPRESSED_RGB));
#endif
#ifdef GL_COMPRESSED_RGBA
  rb_define_const (rbclt_c_cogl, "COMPRESSED_RGBA",
                   INT2FIX (CGL_COMPRESSED_RGBA));
#endif
#ifdef GL_COMPRESSED_SLUMINANCE_ALPHA_EXT
  rb_define_const (rbclt_c_cogl, "COMPRESSED_SLUMINANCE_ALPHA_EXT",
                   INT2FIX (CGL_COMPRESSED_SLUMINANCE_ALPHA_EXT));
#endif
#ifdef GL_COMPRESSED_SLUMINANCE_EXT
  rb_define_const (rbclt_c_cogl, "COMPRESSED_SLUMINANCE_EXT",
                   INT2FIX (CGL_COMPRESSED_SLUMINANCE_EXT));
#endif
#ifdef GL_COMPRESSED_SRGB_ALPHA_EXT
  rb_define_const (rbclt_c_cogl, "COMPRESSED_SRGB_ALPHA_EXT",
                   INT2FIX (CGL_COMPRESSED_SRGB_ALPHA_EXT));
#endif
#ifdef GL_COMPRESSED_SRGB_EXT
  rb_define_const (rbclt_c_cogl, "COMPRESSED_SRGB_EXT",
                   INT2FIX (CGL_COMPRESSED_SRGB_EXT));
#endif
#ifdef GL_COMPRESSED_TEXTURE_FORMATS
  rb_define_const (rbclt_c_cogl, "COMPRESSED_TEXTURE_FORMATS",
                   INT2FIX (CGL_COMPRESSED_TEXTURE_FORMATS));
#endif
#ifdef GL_CONSTANT
  rb_define_const (rbclt_c_cogl, "CONSTANT",
                   INT2FIX (CGL_CONSTANT));
#endif
#ifdef GL_CONSTANT_ALPHA
  rb_define_const (rbclt_c_cogl, "CONSTANT_ALPHA",
                   INT2FIX (CGL_CONSTANT_ALPHA));
#endif
#ifdef GL_CONSTANT_ATTENUATION
  rb_define_const (rbclt_c_cogl, "CONSTANT_ATTENUATION",
                   INT2FIX (CGL_CONSTANT_ATTENUATION));
#endif
#ifdef GL_CONSTANT_BORDER
  rb_define_const (rbclt_c_cogl, "CONSTANT_BORDER",
                   INT2FIX (CGL_CONSTANT_BORDER));
#endif
#ifdef GL_CONSTANT_COLOR
  rb_define_const (rbclt_c_cogl, "CONSTANT_COLOR",
                   INT2FIX (CGL_CONSTANT_COLOR));
#endif
#ifdef GL_CONVOLUTION_BORDER_COLOR
  rb_define_const (rbclt_c_cogl, "CONVOLUTION_BORDER_COLOR",
                   INT2FIX (CGL_CONVOLUTION_BORDER_COLOR));
#endif
#ifdef GL_CONVOLUTION_BORDER_MODE
  rb_define_const (rbclt_c_cogl, "CONVOLUTION_BORDER_MODE",
                   INT2FIX (CGL_CONVOLUTION_BORDER_MODE));
#endif
#ifdef GL_CONVOLUTION_FILTER_BIAS
  rb_define_const (rbclt_c_cogl, "CONVOLUTION_FILTER_BIAS",
                   INT2FIX (CGL_CONVOLUTION_FILTER_BIAS));
#endif
#ifdef GL_CONVOLUTION_FILTER_SCALE
  rb_define_const (rbclt_c_cogl, "CONVOLUTION_FILTER_SCALE",
                   INT2FIX (CGL_CONVOLUTION_FILTER_SCALE));
#endif
#ifdef GL_CONVOLUTION_FORMAT
  rb_define_const (rbclt_c_cogl, "CONVOLUTION_FORMAT",
                   INT2FIX (CGL_CONVOLUTION_FORMAT));
#endif
#ifdef GL_CONVOLUTION_HEIGHT
  rb_define_const (rbclt_c_cogl, "CONVOLUTION_HEIGHT",
                   INT2FIX (CGL_CONVOLUTION_HEIGHT));
#endif
#ifdef GL_CONVOLUTION_WIDTH
  rb_define_const (rbclt_c_cogl, "CONVOLUTION_WIDTH",
                   INT2FIX (CGL_CONVOLUTION_WIDTH));
#endif
#ifdef GL_COPY
  rb_define_const (rbclt_c_cogl, "COPY",
                   INT2FIX (CGL_COPY));
#endif
#ifdef GL_COPY_INVERTED
  rb_define_const (rbclt_c_cogl, "COPY_INVERTED",
                   INT2FIX (CGL_COPY_INVERTED));
#endif
#ifdef GL_COPY_PIXEL_TOKEN
  rb_define_const (rbclt_c_cogl, "COPY_PIXEL_TOKEN",
                   INT2FIX (CGL_COPY_PIXEL_TOKEN));
#endif
#ifdef GL_CULL_FACE
  rb_define_const (rbclt_c_cogl, "CULL_FACE",
                   INT2FIX (CGL_CULL_FACE));
#endif
#ifdef GL_CULL_FACE_MODE
  rb_define_const (rbclt_c_cogl, "CULL_FACE_MODE",
                   INT2FIX (CGL_CULL_FACE_MODE));
#endif
#ifdef GL_CURRENT_BIT
  rb_define_const (rbclt_c_cogl, "CURRENT_BIT",
                   INT2FIX (CGL_CURRENT_BIT));
#endif
#ifdef GL_CURRENT_COLOR
  rb_define_const (rbclt_c_cogl, "CURRENT_COLOR",
                   INT2FIX (CGL_CURRENT_COLOR));
#endif
#ifdef GL_CURRENT_INDEX
  rb_define_const (rbclt_c_cogl, "CURRENT_INDEX",
                   INT2FIX (CGL_CURRENT_INDEX));
#endif
#ifdef GL_CURRENT_NORMAL
  rb_define_const (rbclt_c_cogl, "CURRENT_NORMAL",
                   INT2FIX (CGL_CURRENT_NORMAL));
#endif
#ifdef GL_CURRENT_RASTER_COLOR
  rb_define_const (rbclt_c_cogl, "CURRENT_RASTER_COLOR",
                   INT2FIX (CGL_CURRENT_RASTER_COLOR));
#endif
#ifdef GL_CURRENT_RASTER_DISTANCE
  rb_define_const (rbclt_c_cogl, "CURRENT_RASTER_DISTANCE",
                   INT2FIX (CGL_CURRENT_RASTER_DISTANCE));
#endif
#ifdef GL_CURRENT_RASTER_INDEX
  rb_define_const (rbclt_c_cogl, "CURRENT_RASTER_INDEX",
                   INT2FIX (CGL_CURRENT_RASTER_INDEX));
#endif
#ifdef GL_CURRENT_RASTER_POSITION
  rb_define_const (rbclt_c_cogl, "CURRENT_RASTER_POSITION",
                   INT2FIX (CGL_CURRENT_RASTER_POSITION));
#endif
#ifdef GL_CURRENT_RASTER_POSITION_VALID
  rb_define_const (rbclt_c_cogl, "CURRENT_RASTER_POSITION_VALID",
                   INT2FIX (CGL_CURRENT_RASTER_POSITION_VALID));
#endif
#ifdef GL_CURRENT_RASTER_TEXTURE_COORDS
  rb_define_const (rbclt_c_cogl, "CURRENT_RASTER_TEXTURE_COORDS",
                   INT2FIX (CGL_CURRENT_RASTER_TEXTURE_COORDS));
#endif
#ifdef GL_CURRENT_TEXTURE_COORDS
  rb_define_const (rbclt_c_cogl, "CURRENT_TEXTURE_COORDS",
                   INT2FIX (CGL_CURRENT_TEXTURE_COORDS));
#endif
#ifdef GL_CW
  rb_define_const (rbclt_c_cogl, "CW",
                   INT2FIX (CGL_CW));
#endif
#ifdef GL_DEBUG_ASSERT_MESA
  rb_define_const (rbclt_c_cogl, "DEBUG_ASSERT_MESA",
                   INT2FIX (CGL_DEBUG_ASSERT_MESA));
#endif
#ifdef GL_DEBUG_OBJECT_MESA
  rb_define_const (rbclt_c_cogl, "DEBUG_OBJECT_MESA",
                   INT2FIX (CGL_DEBUG_OBJECT_MESA));
#endif
#ifdef GL_DEBUG_PRINT_MESA
  rb_define_const (rbclt_c_cogl, "DEBUG_PRINT_MESA",
                   INT2FIX (CGL_DEBUG_PRINT_MESA));
#endif
#ifdef GL_DECAL
  rb_define_const (rbclt_c_cogl, "DECAL",
                   INT2FIX (CGL_DECAL));
#endif
#ifdef GL_DECR
  rb_define_const (rbclt_c_cogl, "DECR",
                   INT2FIX (CGL_DECR));
#endif
#ifdef GL_DEPTH
  rb_define_const (rbclt_c_cogl, "DEPTH",
                   INT2FIX (CGL_DEPTH));
#endif
#ifdef GL_DEPTH_BIAS
  rb_define_const (rbclt_c_cogl, "DEPTH_BIAS",
                   INT2FIX (CGL_DEPTH_BIAS));
#endif
#ifdef GL_DEPTH_BITS
  rb_define_const (rbclt_c_cogl, "DEPTH_BITS",
                   INT2FIX (CGL_DEPTH_BITS));
#endif
#ifdef GL_DEPTH_BUFFER_BIT
  rb_define_const (rbclt_c_cogl, "DEPTH_BUFFER_BIT",
                   INT2FIX (CGL_DEPTH_BUFFER_BIT));
#endif
#ifdef GL_DEPTH_CLEAR_VALUE
  rb_define_const (rbclt_c_cogl, "DEPTH_CLEAR_VALUE",
                   INT2FIX (CGL_DEPTH_CLEAR_VALUE));
#endif
#ifdef GL_DEPTH_COMPONENT
  rb_define_const (rbclt_c_cogl, "DEPTH_COMPONENT",
                   INT2FIX (CGL_DEPTH_COMPONENT));
#endif
#ifdef GL_DEPTH_FUNC
  rb_define_const (rbclt_c_cogl, "DEPTH_FUNC",
                   INT2FIX (CGL_DEPTH_FUNC));
#endif
#ifdef GL_DEPTH_RANGE
  rb_define_const (rbclt_c_cogl, "DEPTH_RANGE",
                   INT2FIX (CGL_DEPTH_RANGE));
#endif
#ifdef GL_DEPTH_SCALE
  rb_define_const (rbclt_c_cogl, "DEPTH_SCALE",
                   INT2FIX (CGL_DEPTH_SCALE));
#endif
#ifdef GL_DEPTH_STENCIL_EXT
  rb_define_const (rbclt_c_cogl, "DEPTH_STENCIL_EXT",
                   INT2FIX (CGL_DEPTH_STENCIL_EXT));
#endif
#ifdef GL_DEPTH_STENCIL_MESA
  rb_define_const (rbclt_c_cogl, "DEPTH_STENCIL_MESA",
                   INT2FIX (CGL_DEPTH_STENCIL_MESA));
#endif
#ifdef GL_DEPTH_TEST
  rb_define_const (rbclt_c_cogl, "DEPTH_TEST",
                   INT2FIX (CGL_DEPTH_TEST));
#endif
#ifdef GL_DEPTH_WRITEMASK
  rb_define_const (rbclt_c_cogl, "DEPTH_WRITEMASK",
                   INT2FIX (CGL_DEPTH_WRITEMASK));
#endif
#ifdef GL_DIFFUSE
  rb_define_const (rbclt_c_cogl, "DIFFUSE",
                   INT2FIX (CGL_DIFFUSE));
#endif
#ifdef GL_DITHER
  rb_define_const (rbclt_c_cogl, "DITHER",
                   INT2FIX (CGL_DITHER));
#endif
#ifdef GL_DOMAIN
  rb_define_const (rbclt_c_cogl, "DOMAIN",
                   INT2FIX (CGL_DOMAIN));
#endif
#ifdef GL_DONT_CARE
  rb_define_const (rbclt_c_cogl, "DONT_CARE",
                   INT2FIX (CGL_DONT_CARE));
#endif
#ifdef GL_DOUBLE
  rb_define_const (rbclt_c_cogl, "DOUBLE",
                   INT2FIX (CGL_DOUBLE));
#endif
#ifdef GL_DOUBLEBUFFER
  rb_define_const (rbclt_c_cogl, "DOUBLEBUFFER",
                   INT2FIX (CGL_DOUBLEBUFFER));
#endif
#ifdef GL_DRAW_BUFFER
  rb_define_const (rbclt_c_cogl, "DRAW_BUFFER",
                   INT2FIX (CGL_DRAW_BUFFER));
#endif
#ifdef GL_DRAW_FRAMEBUFFER_BINDING_EXT
  rb_define_const (rbclt_c_cogl, "DRAW_FRAMEBUFFER_BINDING_EXT",
                   INT2FIX (CGL_DRAW_FRAMEBUFFER_BINDING_EXT));
#endif
#ifdef GL_DRAW_FRAMEBUFFER_EXT
  rb_define_const (rbclt_c_cogl, "DRAW_FRAMEBUFFER_EXT",
                   INT2FIX (CGL_DRAW_FRAMEBUFFER_EXT));
#endif
#ifdef GL_DRAW_PIXEL_TOKEN
  rb_define_const (rbclt_c_cogl, "DRAW_PIXEL_TOKEN",
                   INT2FIX (CGL_DRAW_PIXEL_TOKEN));
#endif
#ifdef GL_DST_ALPHA
  rb_define_const (rbclt_c_cogl, "DST_ALPHA",
                   INT2FIX (CGL_DST_ALPHA));
#endif
#ifdef GL_DST_COLOR
  rb_define_const (rbclt_c_cogl, "DST_COLOR",
                   INT2FIX (CGL_DST_COLOR));
#endif
#ifdef GL_EDGE_FLAG
  rb_define_const (rbclt_c_cogl, "EDGE_FLAG",
                   INT2FIX (CGL_EDGE_FLAG));
#endif
#ifdef GL_EDGE_FLAG_ARRAY
  rb_define_const (rbclt_c_cogl, "EDGE_FLAG_ARRAY",
                   INT2FIX (CGL_EDGE_FLAG_ARRAY));
#endif
#ifdef GL_EDGE_FLAG_ARRAY_POINTER
  rb_define_const (rbclt_c_cogl, "EDGE_FLAG_ARRAY_POINTER",
                   INT2FIX (CGL_EDGE_FLAG_ARRAY_POINTER));
#endif
#ifdef GL_EDGE_FLAG_ARRAY_STRIDE
  rb_define_const (rbclt_c_cogl, "EDGE_FLAG_ARRAY_STRIDE",
                   INT2FIX (CGL_EDGE_FLAG_ARRAY_STRIDE));
#endif
#ifdef GL_EMISSION
  rb_define_const (rbclt_c_cogl, "EMISSION",
                   INT2FIX (CGL_EMISSION));
#endif
#ifdef GL_ENABLE_BIT
  rb_define_const (rbclt_c_cogl, "ENABLE_BIT",
                   INT2FIX (CGL_ENABLE_BIT));
#endif
#ifdef GL_EQUAL
  rb_define_const (rbclt_c_cogl, "EQUAL",
                   INT2FIX (CGL_EQUAL));
#endif
#ifdef GL_EQUIV
  rb_define_const (rbclt_c_cogl, "EQUIV",
                   INT2FIX (CGL_EQUIV));
#endif
#ifdef GL_EVAL_BIT
  rb_define_const (rbclt_c_cogl, "EVAL_BIT",
                   INT2FIX (CGL_EVAL_BIT));
#endif
#ifdef GL_EXP
  rb_define_const (rbclt_c_cogl, "EXP",
                   INT2FIX (CGL_EXP));
#endif
#ifdef GL_EXTENSIONS
  rb_define_const (rbclt_c_cogl, "EXTENSIONS",
                   INT2FIX (CGL_EXTENSIONS));
#endif
#ifdef GL_EYE_LINEAR
  rb_define_const (rbclt_c_cogl, "EYE_LINEAR",
                   INT2FIX (CGL_EYE_LINEAR));
#endif
#ifdef GL_EYE_PLANE
  rb_define_const (rbclt_c_cogl, "EYE_PLANE",
                   INT2FIX (CGL_EYE_PLANE));
#endif
#ifdef GL_FALSE
  rb_define_const (rbclt_c_cogl, "FALSE",
                   INT2FIX (CGL_FALSE));
#endif
#ifdef GL_FASTEST
  rb_define_const (rbclt_c_cogl, "FASTEST",
                   INT2FIX (CGL_FASTEST));
#endif
#ifdef GL_FEEDBACK
  rb_define_const (rbclt_c_cogl, "FEEDBACK",
                   INT2FIX (CGL_FEEDBACK));
#endif
#ifdef GL_FEEDBACK_BUFFER_POINTER
  rb_define_const (rbclt_c_cogl, "FEEDBACK_BUFFER_POINTER",
                   INT2FIX (CGL_FEEDBACK_BUFFER_POINTER));
#endif
#ifdef GL_FEEDBACK_BUFFER_SIZE
  rb_define_const (rbclt_c_cogl, "FEEDBACK_BUFFER_SIZE",
                   INT2FIX (CGL_FEEDBACK_BUFFER_SIZE));
#endif
#ifdef GL_FEEDBACK_BUFFER_TYPE
  rb_define_const (rbclt_c_cogl, "FEEDBACK_BUFFER_TYPE",
                   INT2FIX (CGL_FEEDBACK_BUFFER_TYPE));
#endif
#ifdef GL_FILL
  rb_define_const (rbclt_c_cogl, "FILL",
                   INT2FIX (CGL_FILL));
#endif
#ifdef GL_FLAT
  rb_define_const (rbclt_c_cogl, "FLAT",
                   INT2FIX (CGL_FLAT));
#endif
#ifdef GL_FLOAT
  rb_define_const (rbclt_c_cogl, "FLOAT",
                   INT2FIX (CGL_FLOAT));
#endif
#ifdef GL_FOG
  rb_define_const (rbclt_c_cogl, "FOG",
                   INT2FIX (CGL_FOG));
#endif
#ifdef GL_FOG_BIT
  rb_define_const (rbclt_c_cogl, "FOG_BIT",
                   INT2FIX (CGL_FOG_BIT));
#endif
#ifdef GL_FOG_COLOR
  rb_define_const (rbclt_c_cogl, "FOG_COLOR",
                   INT2FIX (CGL_FOG_COLOR));
#endif
#ifdef GL_FOG_DENSITY
  rb_define_const (rbclt_c_cogl, "FOG_DENSITY",
                   INT2FIX (CGL_FOG_DENSITY));
#endif
#ifdef GL_FOG_END
  rb_define_const (rbclt_c_cogl, "FOG_END",
                   INT2FIX (CGL_FOG_END));
#endif
#ifdef GL_FOG_HINT
  rb_define_const (rbclt_c_cogl, "FOG_HINT",
                   INT2FIX (CGL_FOG_HINT));
#endif
#ifdef GL_FOG_INDEX
  rb_define_const (rbclt_c_cogl, "FOG_INDEX",
                   INT2FIX (CGL_FOG_INDEX));
#endif
#ifdef GL_FOG_MODE
  rb_define_const (rbclt_c_cogl, "FOG_MODE",
                   INT2FIX (CGL_FOG_MODE));
#endif
#ifdef GL_FOG_START
  rb_define_const (rbclt_c_cogl, "FOG_START",
                   INT2FIX (CGL_FOG_START));
#endif
#ifdef GL_FRAGMENT_PROGRAM_CALLBACK_DATA_MESA
  rb_define_const (rbclt_c_cogl, "FRAGMENT_PROGRAM_CALLBACK_DATA_MESA",
                   INT2FIX (CGL_FRAGMENT_PROGRAM_CALLBACK_DATA_MESA));
#endif
#ifdef GL_FRAGMENT_PROGRAM_CALLBACK_FUNC_MESA
  rb_define_const (rbclt_c_cogl, "FRAGMENT_PROGRAM_CALLBACK_FUNC_MESA",
                   INT2FIX (CGL_FRAGMENT_PROGRAM_CALLBACK_FUNC_MESA));
#endif
#ifdef GL_FRAGMENT_PROGRAM_CALLBACK_MESA
  rb_define_const (rbclt_c_cogl, "FRAGMENT_PROGRAM_CALLBACK_MESA",
                   INT2FIX (CGL_FRAGMENT_PROGRAM_CALLBACK_MESA));
#endif
#ifdef GL_FRAGMENT_PROGRAM_POSITION_MESA
  rb_define_const (rbclt_c_cogl, "FRAGMENT_PROGRAM_POSITION_MESA",
                   INT2FIX (CGL_FRAGMENT_PROGRAM_POSITION_MESA));
#endif
#ifdef GL_FRAGMENT_SHADER_ARB
  rb_define_const (rbclt_c_cogl, "FRAGMENT_SHADER",
                   INT2FIX (CGL_FRAGMENT_SHADER));
#endif
#ifdef GL_FRONT
  rb_define_const (rbclt_c_cogl, "FRONT",
                   INT2FIX (CGL_FRONT));
#endif
#ifdef GL_FRONT_AND_BACK
  rb_define_const (rbclt_c_cogl, "FRONT_AND_BACK",
                   INT2FIX (CGL_FRONT_AND_BACK));
#endif
#ifdef GL_FRONT_FACE
  rb_define_const (rbclt_c_cogl, "FRONT_FACE",
                   INT2FIX (CGL_FRONT_FACE));
#endif
#ifdef GL_FRONT_LEFT
  rb_define_const (rbclt_c_cogl, "FRONT_LEFT",
                   INT2FIX (CGL_FRONT_LEFT));
#endif
#ifdef GL_FRONT_RIGHT
  rb_define_const (rbclt_c_cogl, "FRONT_RIGHT",
                   INT2FIX (CGL_FRONT_RIGHT));
#endif
#ifdef GL_FUNC_ADD
  rb_define_const (rbclt_c_cogl, "FUNC_ADD",
                   INT2FIX (CGL_FUNC_ADD));
#endif
#ifdef GL_FUNC_REVERSE_SUBTRACT
  rb_define_const (rbclt_c_cogl, "FUNC_REVERSE_SUBTRACT",
                   INT2FIX (CGL_FUNC_REVERSE_SUBTRACT));
#endif
#ifdef GL_FUNC_SUBTRACT
  rb_define_const (rbclt_c_cogl, "FUNC_SUBTRACT",
                   INT2FIX (CGL_FUNC_SUBTRACT));
#endif
#ifdef GL_GEQUAL
  rb_define_const (rbclt_c_cogl, "GEQUAL",
                   INT2FIX (CGL_GEQUAL));
#endif
#ifdef GL_GREATER
  rb_define_const (rbclt_c_cogl, "GREATER",
                   INT2FIX (CGL_GREATER));
#endif
#ifdef GL_GREEN
  rb_define_const (rbclt_c_cogl, "GREEN",
                   INT2FIX (CGL_GREEN));
#endif
#ifdef GL_GREEN_BIAS
  rb_define_const (rbclt_c_cogl, "GREEN_BIAS",
                   INT2FIX (CGL_GREEN_BIAS));
#endif
#ifdef GL_GREEN_BITS
  rb_define_const (rbclt_c_cogl, "GREEN_BITS",
                   INT2FIX (CGL_GREEN_BITS));
#endif
#ifdef GL_GREEN_SCALE
  rb_define_const (rbclt_c_cogl, "GREEN_SCALE",
                   INT2FIX (CGL_GREEN_SCALE));
#endif
#ifdef GL_HINT_BIT
  rb_define_const (rbclt_c_cogl, "HINT_BIT",
                   INT2FIX (CGL_HINT_BIT));
#endif
#ifdef GL_HISTOGRAM
  rb_define_const (rbclt_c_cogl, "HISTOGRAM",
                   INT2FIX (CGL_HISTOGRAM));
#endif
#ifdef GL_HISTOGRAM_ALPHA_SIZE
  rb_define_const (rbclt_c_cogl, "HISTOGRAM_ALPHA_SIZE",
                   INT2FIX (CGL_HISTOGRAM_ALPHA_SIZE));
#endif
#ifdef GL_HISTOGRAM_BLUE_SIZE
  rb_define_const (rbclt_c_cogl, "HISTOGRAM_BLUE_SIZE",
                   INT2FIX (CGL_HISTOGRAM_BLUE_SIZE));
#endif
#ifdef GL_HISTOGRAM_FORMAT
  rb_define_const (rbclt_c_cogl, "HISTOGRAM_FORMAT",
                   INT2FIX (CGL_HISTOGRAM_FORMAT));
#endif
#ifdef GL_HISTOGRAM_GREEN_SIZE
  rb_define_const (rbclt_c_cogl, "HISTOGRAM_GREEN_SIZE",
                   INT2FIX (CGL_HISTOGRAM_GREEN_SIZE));
#endif
#ifdef GL_HISTOGRAM_LUMINANCE_SIZE
  rb_define_const (rbclt_c_cogl, "HISTOGRAM_LUMINANCE_SIZE",
                   INT2FIX (CGL_HISTOGRAM_LUMINANCE_SIZE));
#endif
#ifdef GL_HISTOGRAM_RED_SIZE
  rb_define_const (rbclt_c_cogl, "HISTOGRAM_RED_SIZE",
                   INT2FIX (CGL_HISTOGRAM_RED_SIZE));
#endif
#ifdef GL_HISTOGRAM_SINK
  rb_define_const (rbclt_c_cogl, "HISTOGRAM_SINK",
                   INT2FIX (CGL_HISTOGRAM_SINK));
#endif
#ifdef GL_HISTOGRAM_WIDTH
  rb_define_const (rbclt_c_cogl, "HISTOGRAM_WIDTH",
                   INT2FIX (CGL_HISTOGRAM_WIDTH));
#endif
#ifdef GL_INCR
  rb_define_const (rbclt_c_cogl, "INCR",
                   INT2FIX (CGL_INCR));
#endif
#ifdef GL_INDEX_ARRAY
  rb_define_const (rbclt_c_cogl, "INDEX_ARRAY",
                   INT2FIX (CGL_INDEX_ARRAY));
#endif
#ifdef GL_INDEX_ARRAY_POINTER
  rb_define_const (rbclt_c_cogl, "INDEX_ARRAY_POINTER",
                   INT2FIX (CGL_INDEX_ARRAY_POINTER));
#endif
#ifdef GL_INDEX_ARRAY_STRIDE
  rb_define_const (rbclt_c_cogl, "INDEX_ARRAY_STRIDE",
                   INT2FIX (CGL_INDEX_ARRAY_STRIDE));
#endif
#ifdef GL_INDEX_ARRAY_TYPE
  rb_define_const (rbclt_c_cogl, "INDEX_ARRAY_TYPE",
                   INT2FIX (CGL_INDEX_ARRAY_TYPE));
#endif
#ifdef GL_INDEX_BITS
  rb_define_const (rbclt_c_cogl, "INDEX_BITS",
                   INT2FIX (CGL_INDEX_BITS));
#endif
#ifdef GL_INDEX_CLEAR_VALUE
  rb_define_const (rbclt_c_cogl, "INDEX_CLEAR_VALUE",
                   INT2FIX (CGL_INDEX_CLEAR_VALUE));
#endif
#ifdef GL_INDEX_LOGIC_OP
  rb_define_const (rbclt_c_cogl, "INDEX_LOGIC_OP",
                   INT2FIX (CGL_INDEX_LOGIC_OP));
#endif
#ifdef GL_INDEX_MODE
  rb_define_const (rbclt_c_cogl, "INDEX_MODE",
                   INT2FIX (CGL_INDEX_MODE));
#endif
#ifdef GL_INDEX_OFFSET
  rb_define_const (rbclt_c_cogl, "INDEX_OFFSET",
                   INT2FIX (CGL_INDEX_OFFSET));
#endif
#ifdef GL_INDEX_SHIFT
  rb_define_const (rbclt_c_cogl, "INDEX_SHIFT",
                   INT2FIX (CGL_INDEX_SHIFT));
#endif
#ifdef GL_INDEX_WRITEMASK
  rb_define_const (rbclt_c_cogl, "INDEX_WRITEMASK",
                   INT2FIX (CGL_INDEX_WRITEMASK));
#endif
#ifdef GL_INT
  rb_define_const (rbclt_c_cogl, "INT",
                   INT2FIX (CGL_INT));
#endif
#ifdef GL_INTENSITY
  rb_define_const (rbclt_c_cogl, "INTENSITY",
                   INT2FIX (CGL_INTENSITY));
#endif
#ifdef GL_INTERPOLATE
  rb_define_const (rbclt_c_cogl, "INTERPOLATE",
                   INT2FIX (CGL_INTERPOLATE));
#endif
#ifdef GL_INVALID_ENUM
  rb_define_const (rbclt_c_cogl, "INVALID_ENUM",
                   INT2FIX (CGL_INVALID_ENUM));
#endif
#ifdef GL_INVALID_OPERATION
  rb_define_const (rbclt_c_cogl, "INVALID_OPERATION",
                   INT2FIX (CGL_INVALID_OPERATION));
#endif
#ifdef GL_INVALID_VALUE
  rb_define_const (rbclt_c_cogl, "INVALID_VALUE",
                   INT2FIX (CGL_INVALID_VALUE));
#endif
#ifdef GL_INVERT
  rb_define_const (rbclt_c_cogl, "INVERT",
                   INT2FIX (CGL_INVERT));
#endif
#ifdef GL_KEEP
  rb_define_const (rbclt_c_cogl, "KEEP",
                   INT2FIX (CGL_KEEP));
#endif
#ifdef GL_LEFT
  rb_define_const (rbclt_c_cogl, "LEFT",
                   INT2FIX (CGL_LEFT));
#endif
#ifdef GL_LEQUAL
  rb_define_const (rbclt_c_cogl, "LEQUAL",
                   INT2FIX (CGL_LEQUAL));
#endif
#ifdef GL_LESS
  rb_define_const (rbclt_c_cogl, "LESS",
                   INT2FIX (CGL_LESS));
#endif
#ifdef GL_LIGHTING
  rb_define_const (rbclt_c_cogl, "LIGHTING",
                   INT2FIX (CGL_LIGHTING));
#endif
#ifdef GL_LIGHTING_BIT
  rb_define_const (rbclt_c_cogl, "LIGHTING_BIT",
                   INT2FIX (CGL_LIGHTING_BIT));
#endif
#ifdef GL_LIGHT_MODEL_AMBIENT
  rb_define_const (rbclt_c_cogl, "LIGHT_MODEL_AMBIENT",
                   INT2FIX (CGL_LIGHT_MODEL_AMBIENT));
#endif
#ifdef GL_LIGHT_MODEL_COLOR_CONTROL
  rb_define_const (rbclt_c_cogl, "LIGHT_MODEL_COLOR_CONTROL",
                   INT2FIX (CGL_LIGHT_MODEL_COLOR_CONTROL));
#endif
#ifdef GL_LIGHT_MODEL_LOCAL_VIEWER
  rb_define_const (rbclt_c_cogl, "LIGHT_MODEL_LOCAL_VIEWER",
                   INT2FIX (CGL_LIGHT_MODEL_LOCAL_VIEWER));
#endif
#ifdef GL_LIGHT_MODEL_TWO_SIDE
  rb_define_const (rbclt_c_cogl, "LIGHT_MODEL_TWO_SIDE",
                   INT2FIX (CGL_LIGHT_MODEL_TWO_SIDE));
#endif
#ifdef GL_LINE
  rb_define_const (rbclt_c_cogl, "LINE",
                   INT2FIX (CGL_LINE));
#endif
#ifdef GL_LINEAR
  rb_define_const (rbclt_c_cogl, "LINEAR",
                   INT2FIX (CGL_LINEAR));
#endif
#ifdef GL_LINEAR_ATTENUATION
  rb_define_const (rbclt_c_cogl, "LINEAR_ATTENUATION",
                   INT2FIX (CGL_LINEAR_ATTENUATION));
#endif
#ifdef GL_LINEAR_MIPMAP_LINEAR
  rb_define_const (rbclt_c_cogl, "LINEAR_MIPMAP_LINEAR",
                   INT2FIX (CGL_LINEAR_MIPMAP_LINEAR));
#endif
#ifdef GL_LINEAR_MIPMAP_NEAREST
  rb_define_const (rbclt_c_cogl, "LINEAR_MIPMAP_NEAREST",
                   INT2FIX (CGL_LINEAR_MIPMAP_NEAREST));
#endif
#ifdef GL_LINES
  rb_define_const (rbclt_c_cogl, "LINES",
                   INT2FIX (CGL_LINES));
#endif
#ifdef GL_LINE_BIT
  rb_define_const (rbclt_c_cogl, "LINE_BIT",
                   INT2FIX (CGL_LINE_BIT));
#endif
#ifdef GL_LINE_LOOP
  rb_define_const (rbclt_c_cogl, "LINE_LOOP",
                   INT2FIX (CGL_LINE_LOOP));
#endif
#ifdef GL_LINE_RESET_TOKEN
  rb_define_const (rbclt_c_cogl, "LINE_RESET_TOKEN",
                   INT2FIX (CGL_LINE_RESET_TOKEN));
#endif
#ifdef GL_LINE_SMOOTH
  rb_define_const (rbclt_c_cogl, "LINE_SMOOTH",
                   INT2FIX (CGL_LINE_SMOOTH));
#endif
#ifdef GL_LINE_SMOOTH_HINT
  rb_define_const (rbclt_c_cogl, "LINE_SMOOTH_HINT",
                   INT2FIX (CGL_LINE_SMOOTH_HINT));
#endif
#ifdef GL_LINE_STIPPLE
  rb_define_const (rbclt_c_cogl, "LINE_STIPPLE",
                   INT2FIX (CGL_LINE_STIPPLE));
#endif
#ifdef GL_LINE_STIPPLE_PATTERN
  rb_define_const (rbclt_c_cogl, "LINE_STIPPLE_PATTERN",
                   INT2FIX (CGL_LINE_STIPPLE_PATTERN));
#endif
#ifdef GL_LINE_STIPPLE_REPEAT
  rb_define_const (rbclt_c_cogl, "LINE_STIPPLE_REPEAT",
                   INT2FIX (CGL_LINE_STIPPLE_REPEAT));
#endif
#ifdef GL_LINE_STRIP
  rb_define_const (rbclt_c_cogl, "LINE_STRIP",
                   INT2FIX (CGL_LINE_STRIP));
#endif
#ifdef GL_LINE_TOKEN
  rb_define_const (rbclt_c_cogl, "LINE_TOKEN",
                   INT2FIX (CGL_LINE_TOKEN));
#endif
#ifdef GL_LINE_WIDTH
  rb_define_const (rbclt_c_cogl, "LINE_WIDTH",
                   INT2FIX (CGL_LINE_WIDTH));
#endif
#ifdef GL_LINE_WIDTH_GRANULARITY
  rb_define_const (rbclt_c_cogl, "LINE_WIDTH_GRANULARITY",
                   INT2FIX (CGL_LINE_WIDTH_GRANULARITY));
#endif
#ifdef GL_LINE_WIDTH_RANGE
  rb_define_const (rbclt_c_cogl, "LINE_WIDTH_RANGE",
                   INT2FIX (CGL_LINE_WIDTH_RANGE));
#endif
#ifdef GL_LIST_BASE
  rb_define_const (rbclt_c_cogl, "LIST_BASE",
                   INT2FIX (CGL_LIST_BASE));
#endif
#ifdef GL_LIST_BIT
  rb_define_const (rbclt_c_cogl, "LIST_BIT",
                   INT2FIX (CGL_LIST_BIT));
#endif
#ifdef GL_LIST_INDEX
  rb_define_const (rbclt_c_cogl, "LIST_INDEX",
                   INT2FIX (CGL_LIST_INDEX));
#endif
#ifdef GL_LIST_MODE
  rb_define_const (rbclt_c_cogl, "LIST_MODE",
                   INT2FIX (CGL_LIST_MODE));
#endif
#ifdef GL_LOAD
  rb_define_const (rbclt_c_cogl, "LOAD",
                   INT2FIX (CGL_LOAD));
#endif
#ifdef GL_LOGIC_OP
  rb_define_const (rbclt_c_cogl, "LOGIC_OP",
                   INT2FIX (CGL_LOGIC_OP));
#endif
#ifdef GL_LOGIC_OP_MODE
  rb_define_const (rbclt_c_cogl, "LOGIC_OP_MODE",
                   INT2FIX (CGL_LOGIC_OP_MODE));
#endif
#ifdef GL_LUMINANCE
  rb_define_const (rbclt_c_cogl, "LUMINANCE",
                   INT2FIX (CGL_LUMINANCE));
#endif
#ifdef GL_LUMINANCE_ALPHA
  rb_define_const (rbclt_c_cogl, "LUMINANCE_ALPHA",
                   INT2FIX (CGL_LUMINANCE_ALPHA));
#endif
#ifdef GL_MAP_COLOR
  rb_define_const (rbclt_c_cogl, "MAP_COLOR",
                   INT2FIX (CGL_MAP_COLOR));
#endif
#ifdef GL_MAP_STENCIL
  rb_define_const (rbclt_c_cogl, "MAP_STENCIL",
                   INT2FIX (CGL_MAP_STENCIL));
#endif
#ifdef GL_MATRIX_MODE
  rb_define_const (rbclt_c_cogl, "MATRIX_MODE",
                   INT2FIX (CGL_MATRIX_MODE));
#endif
#ifdef GL_MAX
  rb_define_const (rbclt_c_cogl, "MAX",
                   INT2FIX (CGL_MAX));
#endif
#ifdef GL_MAX_ATTRIB_STACK_DEPTH
  rb_define_const (rbclt_c_cogl, "MAX_ATTRIB_STACK_DEPTH",
                   INT2FIX (CGL_MAX_ATTRIB_STACK_DEPTH));
#endif
#ifdef GL_MAX_CLIENT_ATTRIB_STACK_DEPTH
  rb_define_const (rbclt_c_cogl, "MAX_CLIENT_ATTRIB_STACK_DEPTH",
                   INT2FIX (CGL_MAX_CLIENT_ATTRIB_STACK_DEPTH));
#endif
#ifdef GL_MAX_CLIP_PLANES
  rb_define_const (rbclt_c_cogl, "MAX_CLIP_PLANES",
                   INT2FIX (CGL_MAX_CLIP_PLANES));
#endif
#ifdef GL_MAX_COLOR_MATRIX_STACK_DEPTH
  rb_define_const (rbclt_c_cogl, "MAX_COLOR_MATRIX_STACK_DEPTH",
                   INT2FIX (CGL_MAX_COLOR_MATRIX_STACK_DEPTH));
#endif
#ifdef GL_MAX_CONVOLUTION_HEIGHT
  rb_define_const (rbclt_c_cogl, "MAX_CONVOLUTION_HEIGHT",
                   INT2FIX (CGL_MAX_CONVOLUTION_HEIGHT));
#endif
#ifdef GL_MAX_CONVOLUTION_WIDTH
  rb_define_const (rbclt_c_cogl, "MAX_CONVOLUTION_WIDTH",
                   INT2FIX (CGL_MAX_CONVOLUTION_WIDTH));
#endif
#ifdef GL_MAX_CUBE_MAP_TEXTURE_SIZE
  rb_define_const (rbclt_c_cogl, "MAX_CUBE_MAP_TEXTURE_SIZE",
                   INT2FIX (CGL_MAX_CUBE_MAP_TEXTURE_SIZE));
#endif
#ifdef GL_MAX_ELEMENTS_INDICES
  rb_define_const (rbclt_c_cogl, "MAX_ELEMENTS_INDICES",
                   INT2FIX (CGL_MAX_ELEMENTS_INDICES));
#endif
#ifdef GL_MAX_ELEMENTS_VERTICES
  rb_define_const (rbclt_c_cogl, "MAX_ELEMENTS_VERTICES",
                   INT2FIX (CGL_MAX_ELEMENTS_VERTICES));
#endif
#ifdef GL_MAX_EVAL_ORDER
  rb_define_const (rbclt_c_cogl, "MAX_EVAL_ORDER",
                   INT2FIX (CGL_MAX_EVAL_ORDER));
#endif
#ifdef GL_MAX_LIGHTS
  rb_define_const (rbclt_c_cogl, "MAX_LIGHTS",
                   INT2FIX (CGL_MAX_LIGHTS));
#endif
#ifdef GL_MAX_LIST_NESTING
  rb_define_const (rbclt_c_cogl, "MAX_LIST_NESTING",
                   INT2FIX (CGL_MAX_LIST_NESTING));
#endif
#ifdef GL_MAX_MODELVIEW_STACK_DEPTH
  rb_define_const (rbclt_c_cogl, "MAX_MODELVIEW_STACK_DEPTH",
                   INT2FIX (CGL_MAX_MODELVIEW_STACK_DEPTH));
#endif
#ifdef GL_MAX_NAME_STACK_DEPTH
  rb_define_const (rbclt_c_cogl, "MAX_NAME_STACK_DEPTH",
                   INT2FIX (CGL_MAX_NAME_STACK_DEPTH));
#endif
#ifdef GL_MAX_PIXEL_MAP_TABLE
  rb_define_const (rbclt_c_cogl, "MAX_PIXEL_MAP_TABLE",
                   INT2FIX (CGL_MAX_PIXEL_MAP_TABLE));
#endif
#ifdef GL_MAX_PROJECTION_STACK_DEPTH
  rb_define_const (rbclt_c_cogl, "MAX_PROJECTION_STACK_DEPTH",
                   INT2FIX (CGL_MAX_PROJECTION_STACK_DEPTH));
#endif
#ifdef GL_MAX_TEXTURE_SIZE
  rb_define_const (rbclt_c_cogl, "MAX_TEXTURE_SIZE",
                   INT2FIX (CGL_MAX_TEXTURE_SIZE));
#endif
#ifdef GL_MAX_TEXTURE_STACK_DEPTH
  rb_define_const (rbclt_c_cogl, "MAX_TEXTURE_STACK_DEPTH",
                   INT2FIX (CGL_MAX_TEXTURE_STACK_DEPTH));
#endif
#ifdef GL_MAX_TEXTURE_UNITS
  rb_define_const (rbclt_c_cogl, "MAX_TEXTURE_UNITS",
                   INT2FIX (CGL_MAX_TEXTURE_UNITS));
#endif
#ifdef GL_MAX_TEXTURE_UNITS_ARB
  rb_define_const (rbclt_c_cogl, "MAX_TEXTURE_UNITS_ARB",
                   INT2FIX (CGL_MAX_TEXTURE_UNITS_ARB));
#endif
#ifdef GL_MAX_VIEWPORT_DIMS
  rb_define_const (rbclt_c_cogl, "MAX_VIEWPORT_DIMS",
                   INT2FIX (CGL_MAX_VIEWPORT_DIMS));
#endif
#ifdef GL_MIN
  rb_define_const (rbclt_c_cogl, "MIN",
                   INT2FIX (CGL_MIN));
#endif
#ifdef GL_MINMAX
  rb_define_const (rbclt_c_cogl, "MINMAX",
                   INT2FIX (CGL_MINMAX));
#endif
#ifdef GL_MINMAX_FORMAT
  rb_define_const (rbclt_c_cogl, "MINMAX_FORMAT",
                   INT2FIX (CGL_MINMAX_FORMAT));
#endif
#ifdef GL_MINMAX_SINK
  rb_define_const (rbclt_c_cogl, "MINMAX_SINK",
                   INT2FIX (CGL_MINMAX_SINK));
#endif
#ifdef GL_MODELVIEW
  rb_define_const (rbclt_c_cogl, "MODELVIEW",
                   INT2FIX (CGL_MODELVIEW));
#endif
#ifdef GL_MODELVIEW_MATRIX
  rb_define_const (rbclt_c_cogl, "MODELVIEW_MATRIX",
                   INT2FIX (CGL_MODELVIEW_MATRIX));
#endif
#ifdef GL_MODELVIEW_STACK_DEPTH
  rb_define_const (rbclt_c_cogl, "MODELVIEW_STACK_DEPTH",
                   INT2FIX (CGL_MODELVIEW_STACK_DEPTH));
#endif
#ifdef GL_MODULATE
  rb_define_const (rbclt_c_cogl, "MODULATE",
                   INT2FIX (CGL_MODULATE));
#endif
#ifdef GL_MULT
  rb_define_const (rbclt_c_cogl, "MULT",
                   INT2FIX (CGL_MULT));
#endif
#ifdef GL_MULTISAMPLE
  rb_define_const (rbclt_c_cogl, "MULTISAMPLE",
                   INT2FIX (CGL_MULTISAMPLE));
#endif
#ifdef GL_MULTISAMPLE_BIT
  rb_define_const (rbclt_c_cogl, "MULTISAMPLE_BIT",
                   INT2FIX (CGL_MULTISAMPLE_BIT));
#endif
#ifdef GL_NAME_STACK_DEPTH
  rb_define_const (rbclt_c_cogl, "NAME_STACK_DEPTH",
                   INT2FIX (CGL_NAME_STACK_DEPTH));
#endif
#ifdef GL_NAND
  rb_define_const (rbclt_c_cogl, "NAND",
                   INT2FIX (CGL_NAND));
#endif
#ifdef GL_NEAREST
  rb_define_const (rbclt_c_cogl, "NEAREST",
                   INT2FIX (CGL_NEAREST));
#endif
#ifdef GL_NEAREST_MIPMAP_LINEAR
  rb_define_const (rbclt_c_cogl, "NEAREST_MIPMAP_LINEAR",
                   INT2FIX (CGL_NEAREST_MIPMAP_LINEAR));
#endif
#ifdef GL_NEAREST_MIPMAP_NEAREST
  rb_define_const (rbclt_c_cogl, "NEAREST_MIPMAP_NEAREST",
                   INT2FIX (CGL_NEAREST_MIPMAP_NEAREST));
#endif
#ifdef GL_NEVER
  rb_define_const (rbclt_c_cogl, "NEVER",
                   INT2FIX (CGL_NEVER));
#endif
#ifdef GL_NICEST
  rb_define_const (rbclt_c_cogl, "NICEST",
                   INT2FIX (CGL_NICEST));
#endif
#ifdef GL_NONE
  rb_define_const (rbclt_c_cogl, "NONE",
                   INT2FIX (CGL_NONE));
#endif
#ifdef GL_NOOP
  rb_define_const (rbclt_c_cogl, "NOOP",
                   INT2FIX (CGL_NOOP));
#endif
#ifdef GL_NOR
  rb_define_const (rbclt_c_cogl, "NOR",
                   INT2FIX (CGL_NOR));
#endif
#ifdef GL_NORMALIZE
  rb_define_const (rbclt_c_cogl, "NORMALIZE",
                   INT2FIX (CGL_NORMALIZE));
#endif
#ifdef GL_NORMAL_ARRAY
  rb_define_const (rbclt_c_cogl, "NORMAL_ARRAY",
                   INT2FIX (CGL_NORMAL_ARRAY));
#endif
#ifdef GL_NORMAL_ARRAY_POINTER
  rb_define_const (rbclt_c_cogl, "NORMAL_ARRAY_POINTER",
                   INT2FIX (CGL_NORMAL_ARRAY_POINTER));
#endif
#ifdef GL_NORMAL_ARRAY_STRIDE
  rb_define_const (rbclt_c_cogl, "NORMAL_ARRAY_STRIDE",
                   INT2FIX (CGL_NORMAL_ARRAY_STRIDE));
#endif
#ifdef GL_NORMAL_ARRAY_TYPE
  rb_define_const (rbclt_c_cogl, "NORMAL_ARRAY_TYPE",
                   INT2FIX (CGL_NORMAL_ARRAY_TYPE));
#endif
#ifdef GL_NORMAL_MAP
  rb_define_const (rbclt_c_cogl, "NORMAL_MAP",
                   INT2FIX (CGL_NORMAL_MAP));
#endif
#ifdef GL_NOTEQUAL
  rb_define_const (rbclt_c_cogl, "NOTEQUAL",
                   INT2FIX (CGL_NOTEQUAL));
#endif
#ifdef GL_NO_ERROR
  rb_define_const (rbclt_c_cogl, "NO_ERROR",
                   INT2FIX (CGL_NO_ERROR));
#endif
#ifdef GL_NUM_COMPRESSED_TEXTURE_FORMATS
  rb_define_const (rbclt_c_cogl, "NUM_COMPRESSED_TEXTURE_FORMATS",
                   INT2FIX (CGL_NUM_COMPRESSED_TEXTURE_FORMATS));
#endif
#ifdef GL_OBJECT_COMPILE_STATUS_ARB
  rb_define_const (rbclt_c_cogl, "OBJECT_COMPILE_STATUS",
                   INT2FIX (CGL_OBJECT_COMPILE_STATUS));
#endif
#ifdef GL_OBJECT_LINEAR
  rb_define_const (rbclt_c_cogl, "OBJECT_LINEAR",
                   INT2FIX (CGL_OBJECT_LINEAR));
#endif
#ifdef GL_OBJECT_PLANE
  rb_define_const (rbclt_c_cogl, "OBJECT_PLANE",
                   INT2FIX (CGL_OBJECT_PLANE));
#endif
#ifdef GL_ONE
  rb_define_const (rbclt_c_cogl, "ONE",
                   INT2FIX (CGL_ONE));
#endif
#ifdef GL_ONE_MINUS_CONSTANT_ALPHA
  rb_define_const (rbclt_c_cogl, "ONE_MINUS_CONSTANT_ALPHA",
                   INT2FIX (CGL_ONE_MINUS_CONSTANT_ALPHA));
#endif
#ifdef GL_ONE_MINUS_CONSTANT_COLOR
  rb_define_const (rbclt_c_cogl, "ONE_MINUS_CONSTANT_COLOR",
                   INT2FIX (CGL_ONE_MINUS_CONSTANT_COLOR));
#endif
#ifdef GL_ONE_MINUS_DST_ALPHA
  rb_define_const (rbclt_c_cogl, "ONE_MINUS_DST_ALPHA",
                   INT2FIX (CGL_ONE_MINUS_DST_ALPHA));
#endif
#ifdef GL_ONE_MINUS_DST_COLOR
  rb_define_const (rbclt_c_cogl, "ONE_MINUS_DST_COLOR",
                   INT2FIX (CGL_ONE_MINUS_DST_COLOR));
#endif
#ifdef GL_ONE_MINUS_SRC_ALPHA
  rb_define_const (rbclt_c_cogl, "ONE_MINUS_SRC_ALPHA",
                   INT2FIX (CGL_ONE_MINUS_SRC_ALPHA));
#endif
#ifdef GL_ONE_MINUS_SRC_COLOR
  rb_define_const (rbclt_c_cogl, "ONE_MINUS_SRC_COLOR",
                   INT2FIX (CGL_ONE_MINUS_SRC_COLOR));
#endif
#ifdef GL_OR
  rb_define_const (rbclt_c_cogl, "OR",
                   INT2FIX (CGL_OR));
#endif
#ifdef GL_ORDER
  rb_define_const (rbclt_c_cogl, "ORDER",
                   INT2FIX (CGL_ORDER));
#endif
#ifdef GL_OR_INVERTED
  rb_define_const (rbclt_c_cogl, "OR_INVERTED",
                   INT2FIX (CGL_OR_INVERTED));
#endif
#ifdef GL_OR_REVERSE
  rb_define_const (rbclt_c_cogl, "OR_REVERSE",
                   INT2FIX (CGL_OR_REVERSE));
#endif
#ifdef GL_OUT_OF_MEMORY
  rb_define_const (rbclt_c_cogl, "OUT_OF_MEMORY",
                   INT2FIX (CGL_OUT_OF_MEMORY));
#endif
#ifdef GL_PACK_ALIGNMENT
  rb_define_const (rbclt_c_cogl, "PACK_ALIGNMENT",
                   INT2FIX (CGL_PACK_ALIGNMENT));
#endif
#ifdef GL_PACK_IMAGE_HEIGHT
  rb_define_const (rbclt_c_cogl, "PACK_IMAGE_HEIGHT",
                   INT2FIX (CGL_PACK_IMAGE_HEIGHT));
#endif
#ifdef GL_PACK_LSB_FIRST
  rb_define_const (rbclt_c_cogl, "PACK_LSB_FIRST",
                   INT2FIX (CGL_PACK_LSB_FIRST));
#endif
#ifdef GL_PACK_ROW_LENGTH
  rb_define_const (rbclt_c_cogl, "PACK_ROW_LENGTH",
                   INT2FIX (CGL_PACK_ROW_LENGTH));
#endif
#ifdef GL_PACK_SKIP_IMAGES
  rb_define_const (rbclt_c_cogl, "PACK_SKIP_IMAGES",
                   INT2FIX (CGL_PACK_SKIP_IMAGES));
#endif
#ifdef GL_PACK_SKIP_PIXELS
  rb_define_const (rbclt_c_cogl, "PACK_SKIP_PIXELS",
                   INT2FIX (CGL_PACK_SKIP_PIXELS));
#endif
#ifdef GL_PACK_SKIP_ROWS
  rb_define_const (rbclt_c_cogl, "PACK_SKIP_ROWS",
                   INT2FIX (CGL_PACK_SKIP_ROWS));
#endif
#ifdef GL_PACK_SWAP_BYTES
  rb_define_const (rbclt_c_cogl, "PACK_SWAP_BYTES",
                   INT2FIX (CGL_PACK_SWAP_BYTES));
#endif
#ifdef GL_PASS_THROUGH_TOKEN
  rb_define_const (rbclt_c_cogl, "PASS_THROUGH_TOKEN",
                   INT2FIX (CGL_PASS_THROUGH_TOKEN));
#endif
#ifdef GL_PERSPECTIVE_CORRECTION_HINT
  rb_define_const (rbclt_c_cogl, "PERSPECTIVE_CORRECTION_HINT",
                   INT2FIX (CGL_PERSPECTIVE_CORRECTION_HINT));
#endif
#ifdef GL_PIXEL_MAP_A_TO_A
  rb_define_const (rbclt_c_cogl, "PIXEL_MAP_A_TO_A",
                   INT2FIX (CGL_PIXEL_MAP_A_TO_A));
#endif
#ifdef GL_PIXEL_MAP_A_TO_A_SIZE
  rb_define_const (rbclt_c_cogl, "PIXEL_MAP_A_TO_A_SIZE",
                   INT2FIX (CGL_PIXEL_MAP_A_TO_A_SIZE));
#endif
#ifdef GL_PIXEL_MAP_B_TO_B
  rb_define_const (rbclt_c_cogl, "PIXEL_MAP_B_TO_B",
                   INT2FIX (CGL_PIXEL_MAP_B_TO_B));
#endif
#ifdef GL_PIXEL_MAP_B_TO_B_SIZE
  rb_define_const (rbclt_c_cogl, "PIXEL_MAP_B_TO_B_SIZE",
                   INT2FIX (CGL_PIXEL_MAP_B_TO_B_SIZE));
#endif
#ifdef GL_PIXEL_MAP_G_TO_G
  rb_define_const (rbclt_c_cogl, "PIXEL_MAP_G_TO_G",
                   INT2FIX (CGL_PIXEL_MAP_G_TO_G));
#endif
#ifdef GL_PIXEL_MAP_G_TO_G_SIZE
  rb_define_const (rbclt_c_cogl, "PIXEL_MAP_G_TO_G_SIZE",
                   INT2FIX (CGL_PIXEL_MAP_G_TO_G_SIZE));
#endif
#ifdef GL_PIXEL_MAP_I_TO_A
  rb_define_const (rbclt_c_cogl, "PIXEL_MAP_I_TO_A",
                   INT2FIX (CGL_PIXEL_MAP_I_TO_A));
#endif
#ifdef GL_PIXEL_MAP_I_TO_A_SIZE
  rb_define_const (rbclt_c_cogl, "PIXEL_MAP_I_TO_A_SIZE",
                   INT2FIX (CGL_PIXEL_MAP_I_TO_A_SIZE));
#endif
#ifdef GL_PIXEL_MAP_I_TO_B
  rb_define_const (rbclt_c_cogl, "PIXEL_MAP_I_TO_B",
                   INT2FIX (CGL_PIXEL_MAP_I_TO_B));
#endif
#ifdef GL_PIXEL_MAP_I_TO_B_SIZE
  rb_define_const (rbclt_c_cogl, "PIXEL_MAP_I_TO_B_SIZE",
                   INT2FIX (CGL_PIXEL_MAP_I_TO_B_SIZE));
#endif
#ifdef GL_PIXEL_MAP_I_TO_G
  rb_define_const (rbclt_c_cogl, "PIXEL_MAP_I_TO_G",
                   INT2FIX (CGL_PIXEL_MAP_I_TO_G));
#endif
#ifdef GL_PIXEL_MAP_I_TO_G_SIZE
  rb_define_const (rbclt_c_cogl, "PIXEL_MAP_I_TO_G_SIZE",
                   INT2FIX (CGL_PIXEL_MAP_I_TO_G_SIZE));
#endif
#ifdef GL_PIXEL_MAP_I_TO_I
  rb_define_const (rbclt_c_cogl, "PIXEL_MAP_I_TO_I",
                   INT2FIX (CGL_PIXEL_MAP_I_TO_I));
#endif
#ifdef GL_PIXEL_MAP_I_TO_I_SIZE
  rb_define_const (rbclt_c_cogl, "PIXEL_MAP_I_TO_I_SIZE",
                   INT2FIX (CGL_PIXEL_MAP_I_TO_I_SIZE));
#endif
#ifdef GL_PIXEL_MAP_I_TO_R
  rb_define_const (rbclt_c_cogl, "PIXEL_MAP_I_TO_R",
                   INT2FIX (CGL_PIXEL_MAP_I_TO_R));
#endif
#ifdef GL_PIXEL_MAP_I_TO_R_SIZE
  rb_define_const (rbclt_c_cogl, "PIXEL_MAP_I_TO_R_SIZE",
                   INT2FIX (CGL_PIXEL_MAP_I_TO_R_SIZE));
#endif
#ifdef GL_PIXEL_MAP_R_TO_R
  rb_define_const (rbclt_c_cogl, "PIXEL_MAP_R_TO_R",
                   INT2FIX (CGL_PIXEL_MAP_R_TO_R));
#endif
#ifdef GL_PIXEL_MAP_R_TO_R_SIZE
  rb_define_const (rbclt_c_cogl, "PIXEL_MAP_R_TO_R_SIZE",
                   INT2FIX (CGL_PIXEL_MAP_R_TO_R_SIZE));
#endif
#ifdef GL_PIXEL_MAP_S_TO_S
  rb_define_const (rbclt_c_cogl, "PIXEL_MAP_S_TO_S",
                   INT2FIX (CGL_PIXEL_MAP_S_TO_S));
#endif
#ifdef GL_PIXEL_MAP_S_TO_S_SIZE
  rb_define_const (rbclt_c_cogl, "PIXEL_MAP_S_TO_S_SIZE",
                   INT2FIX (CGL_PIXEL_MAP_S_TO_S_SIZE));
#endif
#ifdef GL_PIXEL_MODE_BIT
  rb_define_const (rbclt_c_cogl, "PIXEL_MODE_BIT",
                   INT2FIX (CGL_PIXEL_MODE_BIT));
#endif
#ifdef GL_POINT
  rb_define_const (rbclt_c_cogl, "POINT",
                   INT2FIX (CGL_POINT));
#endif
#ifdef GL_POINTS
  rb_define_const (rbclt_c_cogl, "POINTS",
                   INT2FIX (CGL_POINTS));
#endif
#ifdef GL_POINT_BIT
  rb_define_const (rbclt_c_cogl, "POINT_BIT",
                   INT2FIX (CGL_POINT_BIT));
#endif
#ifdef GL_POINT_SIZE
  rb_define_const (rbclt_c_cogl, "POINT_SIZE",
                   INT2FIX (CGL_POINT_SIZE));
#endif
#ifdef GL_POINT_SIZE_GRANULARITY
  rb_define_const (rbclt_c_cogl, "POINT_SIZE_GRANULARITY",
                   INT2FIX (CGL_POINT_SIZE_GRANULARITY));
#endif
#ifdef GL_POINT_SIZE_RANGE
  rb_define_const (rbclt_c_cogl, "POINT_SIZE_RANGE",
                   INT2FIX (CGL_POINT_SIZE_RANGE));
#endif
#ifdef GL_POINT_SMOOTH
  rb_define_const (rbclt_c_cogl, "POINT_SMOOTH",
                   INT2FIX (CGL_POINT_SMOOTH));
#endif
#ifdef GL_POINT_SMOOTH_HINT
  rb_define_const (rbclt_c_cogl, "POINT_SMOOTH_HINT",
                   INT2FIX (CGL_POINT_SMOOTH_HINT));
#endif
#ifdef GL_POINT_TOKEN
  rb_define_const (rbclt_c_cogl, "POINT_TOKEN",
                   INT2FIX (CGL_POINT_TOKEN));
#endif
#ifdef GL_POLYGON
  rb_define_const (rbclt_c_cogl, "POLYGON",
                   INT2FIX (CGL_POLYGON));
#endif
#ifdef GL_POLYGON_BIT
  rb_define_const (rbclt_c_cogl, "POLYGON_BIT",
                   INT2FIX (CGL_POLYGON_BIT));
#endif
#ifdef GL_POLYGON_MODE
  rb_define_const (rbclt_c_cogl, "POLYGON_MODE",
                   INT2FIX (CGL_POLYGON_MODE));
#endif
#ifdef GL_POLYGON_OFFSET_FACTOR
  rb_define_const (rbclt_c_cogl, "POLYGON_OFFSET_FACTOR",
                   INT2FIX (CGL_POLYGON_OFFSET_FACTOR));
#endif
#ifdef GL_POLYGON_OFFSET_FILL
  rb_define_const (rbclt_c_cogl, "POLYGON_OFFSET_FILL",
                   INT2FIX (CGL_POLYGON_OFFSET_FILL));
#endif
#ifdef GL_POLYGON_OFFSET_LINE
  rb_define_const (rbclt_c_cogl, "POLYGON_OFFSET_LINE",
                   INT2FIX (CGL_POLYGON_OFFSET_LINE));
#endif
#ifdef GL_POLYGON_OFFSET_POINT
  rb_define_const (rbclt_c_cogl, "POLYGON_OFFSET_POINT",
                   INT2FIX (CGL_POLYGON_OFFSET_POINT));
#endif
#ifdef GL_POLYGON_OFFSET_UNITS
  rb_define_const (rbclt_c_cogl, "POLYGON_OFFSET_UNITS",
                   INT2FIX (CGL_POLYGON_OFFSET_UNITS));
#endif
#ifdef GL_POLYGON_SMOOTH
  rb_define_const (rbclt_c_cogl, "POLYGON_SMOOTH",
                   INT2FIX (CGL_POLYGON_SMOOTH));
#endif
#ifdef GL_POLYGON_SMOOTH_HINT
  rb_define_const (rbclt_c_cogl, "POLYGON_SMOOTH_HINT",
                   INT2FIX (CGL_POLYGON_SMOOTH_HINT));
#endif
#ifdef GL_POLYGON_STIPPLE
  rb_define_const (rbclt_c_cogl, "POLYGON_STIPPLE",
                   INT2FIX (CGL_POLYGON_STIPPLE));
#endif
#ifdef GL_POLYGON_STIPPLE_BIT
  rb_define_const (rbclt_c_cogl, "POLYGON_STIPPLE_BIT",
                   INT2FIX (CGL_POLYGON_STIPPLE_BIT));
#endif
#ifdef GL_POLYGON_TOKEN
  rb_define_const (rbclt_c_cogl, "POLYGON_TOKEN",
                   INT2FIX (CGL_POLYGON_TOKEN));
#endif
#ifdef GL_POSITION
  rb_define_const (rbclt_c_cogl, "POSITION",
                   INT2FIX (CGL_POSITION));
#endif
#ifdef GL_POST_COLOR_MATRIX_ALPHA_BIAS
  rb_define_const (rbclt_c_cogl, "POST_COLOR_MATRIX_ALPHA_BIAS",
                   INT2FIX (CGL_POST_COLOR_MATRIX_ALPHA_BIAS));
#endif
#ifdef GL_POST_COLOR_MATRIX_ALPHA_SCALE
  rb_define_const (rbclt_c_cogl, "POST_COLOR_MATRIX_ALPHA_SCALE",
                   INT2FIX (CGL_POST_COLOR_MATRIX_ALPHA_SCALE));
#endif
#ifdef GL_POST_COLOR_MATRIX_BLUE_BIAS
  rb_define_const (rbclt_c_cogl, "POST_COLOR_MATRIX_BLUE_BIAS",
                   INT2FIX (CGL_POST_COLOR_MATRIX_BLUE_BIAS));
#endif
#ifdef GL_POST_COLOR_MATRIX_BLUE_SCALE
  rb_define_const (rbclt_c_cogl, "POST_COLOR_MATRIX_BLUE_SCALE",
                   INT2FIX (CGL_POST_COLOR_MATRIX_BLUE_SCALE));
#endif
#ifdef GL_POST_COLOR_MATRIX_COLOR_TABLE
  rb_define_const (rbclt_c_cogl, "POST_COLOR_MATRIX_COLOR_TABLE",
                   INT2FIX (CGL_POST_COLOR_MATRIX_COLOR_TABLE));
#endif
#ifdef GL_POST_COLOR_MATRIX_GREEN_BIAS
  rb_define_const (rbclt_c_cogl, "POST_COLOR_MATRIX_GREEN_BIAS",
                   INT2FIX (CGL_POST_COLOR_MATRIX_GREEN_BIAS));
#endif
#ifdef GL_POST_COLOR_MATRIX_GREEN_SCALE
  rb_define_const (rbclt_c_cogl, "POST_COLOR_MATRIX_GREEN_SCALE",
                   INT2FIX (CGL_POST_COLOR_MATRIX_GREEN_SCALE));
#endif
#ifdef GL_POST_COLOR_MATRIX_RED_BIAS
  rb_define_const (rbclt_c_cogl, "POST_COLOR_MATRIX_RED_BIAS",
                   INT2FIX (CGL_POST_COLOR_MATRIX_RED_BIAS));
#endif
#ifdef GL_POST_COLOR_MATRIX_RED_SCALE
  rb_define_const (rbclt_c_cogl, "POST_COLOR_MATRIX_RED_SCALE",
                   INT2FIX (CGL_POST_COLOR_MATRIX_RED_SCALE));
#endif
#ifdef GL_POST_CONVOLUTION_ALPHA_BIAS
  rb_define_const (rbclt_c_cogl, "POST_CONVOLUTION_ALPHA_BIAS",
                   INT2FIX (CGL_POST_CONVOLUTION_ALPHA_BIAS));
#endif
#ifdef GL_POST_CONVOLUTION_ALPHA_SCALE
  rb_define_const (rbclt_c_cogl, "POST_CONVOLUTION_ALPHA_SCALE",
                   INT2FIX (CGL_POST_CONVOLUTION_ALPHA_SCALE));
#endif
#ifdef GL_POST_CONVOLUTION_BLUE_BIAS
  rb_define_const (rbclt_c_cogl, "POST_CONVOLUTION_BLUE_BIAS",
                   INT2FIX (CGL_POST_CONVOLUTION_BLUE_BIAS));
#endif
#ifdef GL_POST_CONVOLUTION_BLUE_SCALE
  rb_define_const (rbclt_c_cogl, "POST_CONVOLUTION_BLUE_SCALE",
                   INT2FIX (CGL_POST_CONVOLUTION_BLUE_SCALE));
#endif
#ifdef GL_POST_CONVOLUTION_COLOR_TABLE
  rb_define_const (rbclt_c_cogl, "POST_CONVOLUTION_COLOR_TABLE",
                   INT2FIX (CGL_POST_CONVOLUTION_COLOR_TABLE));
#endif
#ifdef GL_POST_CONVOLUTION_GREEN_BIAS
  rb_define_const (rbclt_c_cogl, "POST_CONVOLUTION_GREEN_BIAS",
                   INT2FIX (CGL_POST_CONVOLUTION_GREEN_BIAS));
#endif
#ifdef GL_POST_CONVOLUTION_GREEN_SCALE
  rb_define_const (rbclt_c_cogl, "POST_CONVOLUTION_GREEN_SCALE",
                   INT2FIX (CGL_POST_CONVOLUTION_GREEN_SCALE));
#endif
#ifdef GL_POST_CONVOLUTION_RED_BIAS
  rb_define_const (rbclt_c_cogl, "POST_CONVOLUTION_RED_BIAS",
                   INT2FIX (CGL_POST_CONVOLUTION_RED_BIAS));
#endif
#ifdef GL_POST_CONVOLUTION_RED_SCALE
  rb_define_const (rbclt_c_cogl, "POST_CONVOLUTION_RED_SCALE",
                   INT2FIX (CGL_POST_CONVOLUTION_RED_SCALE));
#endif
#ifdef GL_PREVIOUS
  rb_define_const (rbclt_c_cogl, "PREVIOUS",
                   INT2FIX (CGL_PREVIOUS));
#endif
#ifdef GL_PRIMARY_COLOR
  rb_define_const (rbclt_c_cogl, "PRIMARY_COLOR",
                   INT2FIX (CGL_PRIMARY_COLOR));
#endif
#ifdef GL_PROJECTION
  rb_define_const (rbclt_c_cogl, "PROJECTION",
                   INT2FIX (CGL_PROJECTION));
#endif
#ifdef GL_PROJECTION_MATRIX
  rb_define_const (rbclt_c_cogl, "PROJECTION_MATRIX",
                   INT2FIX (CGL_PROJECTION_MATRIX));
#endif
#ifdef GL_PROJECTION_STACK_DEPTH
  rb_define_const (rbclt_c_cogl, "PROJECTION_STACK_DEPTH",
                   INT2FIX (CGL_PROJECTION_STACK_DEPTH));
#endif
#ifdef GL_PROXY_COLOR_TABLE
  rb_define_const (rbclt_c_cogl, "PROXY_COLOR_TABLE",
                   INT2FIX (CGL_PROXY_COLOR_TABLE));
#endif
#ifdef GL_PROXY_HISTOGRAM
  rb_define_const (rbclt_c_cogl, "PROXY_HISTOGRAM",
                   INT2FIX (CGL_PROXY_HISTOGRAM));
#endif
#ifdef GL_PROXY_POST_COLOR_MATRIX_COLOR_TABLE
  rb_define_const (rbclt_c_cogl, "PROXY_POST_COLOR_MATRIX_COLOR_TABLE",
                   INT2FIX (CGL_PROXY_POST_COLOR_MATRIX_COLOR_TABLE));
#endif
#ifdef GL_PROXY_POST_CONVOLUTION_COLOR_TABLE
  rb_define_const (rbclt_c_cogl, "PROXY_POST_CONVOLUTION_COLOR_TABLE",
                   INT2FIX (CGL_PROXY_POST_CONVOLUTION_COLOR_TABLE));
#endif
#ifdef GL_PROXY_TEXTURE_CUBE_MAP
  rb_define_const (rbclt_c_cogl, "PROXY_TEXTURE_CUBE_MAP",
                   INT2FIX (CGL_PROXY_TEXTURE_CUBE_MAP));
#endif
#ifdef GL_Q
  rb_define_const (rbclt_c_cogl, "Q",
                   INT2FIX (CGL_Q));
#endif
#ifdef GL_QUADRATIC_ATTENUATION
  rb_define_const (rbclt_c_cogl, "QUADRATIC_ATTENUATION",
                   INT2FIX (CGL_QUADRATIC_ATTENUATION));
#endif
#ifdef GL_QUADS
  rb_define_const (rbclt_c_cogl, "QUADS",
                   INT2FIX (CGL_QUADS));
#endif
#ifdef GL_QUAD_STRIP
  rb_define_const (rbclt_c_cogl, "QUAD_STRIP",
                   INT2FIX (CGL_QUAD_STRIP));
#endif
#ifdef GL_R
  rb_define_const (rbclt_c_cogl, "R",
                   INT2FIX (CGL_R));
#endif
#ifdef GL_READ_BUFFER
  rb_define_const (rbclt_c_cogl, "READ_BUFFER",
                   INT2FIX (CGL_READ_BUFFER));
#endif
#ifdef GL_READ_FRAMEBUFFER_BINDING_EXT
  rb_define_const (rbclt_c_cogl, "READ_FRAMEBUFFER_BINDING_EXT",
                   INT2FIX (CGL_READ_FRAMEBUFFER_BINDING_EXT));
#endif
#ifdef GL_READ_FRAMEBUFFER_EXT
  rb_define_const (rbclt_c_cogl, "READ_FRAMEBUFFER_EXT",
                   INT2FIX (CGL_READ_FRAMEBUFFER_EXT));
#endif
#ifdef GL_RED
  rb_define_const (rbclt_c_cogl, "RED",
                   INT2FIX (CGL_RED));
#endif
#ifdef GL_REDUCE
  rb_define_const (rbclt_c_cogl, "REDUCE",
                   INT2FIX (CGL_REDUCE));
#endif
#ifdef GL_RED_BIAS
  rb_define_const (rbclt_c_cogl, "RED_BIAS",
                   INT2FIX (CGL_RED_BIAS));
#endif
#ifdef GL_RED_BITS
  rb_define_const (rbclt_c_cogl, "RED_BITS",
                   INT2FIX (CGL_RED_BITS));
#endif
#ifdef GL_RED_SCALE
  rb_define_const (rbclt_c_cogl, "RED_SCALE",
                   INT2FIX (CGL_RED_SCALE));
#endif
#ifdef GL_REFLECTION_MAP
  rb_define_const (rbclt_c_cogl, "REFLECTION_MAP",
                   INT2FIX (CGL_REFLECTION_MAP));
#endif
#ifdef GL_RENDER
  rb_define_const (rbclt_c_cogl, "RENDER",
                   INT2FIX (CGL_RENDER));
#endif
#ifdef GL_RENDERER
  rb_define_const (rbclt_c_cogl, "RENDERER",
                   INT2FIX (CGL_RENDERER));
#endif
#ifdef GL_RENDER_MODE
  rb_define_const (rbclt_c_cogl, "RENDER_MODE",
                   INT2FIX (CGL_RENDER_MODE));
#endif
#ifdef GL_REPEAT
  rb_define_const (rbclt_c_cogl, "REPEAT",
                   INT2FIX (CGL_REPEAT));
#endif
#ifdef GL_REPLACE
  rb_define_const (rbclt_c_cogl, "REPLACE",
                   INT2FIX (CGL_REPLACE));
#endif
#ifdef GL_REPLICATE_BORDER
  rb_define_const (rbclt_c_cogl, "REPLICATE_BORDER",
                   INT2FIX (CGL_REPLICATE_BORDER));
#endif
#ifdef GL_RESCALE_NORMAL
  rb_define_const (rbclt_c_cogl, "RESCALE_NORMAL",
                   INT2FIX (CGL_RESCALE_NORMAL));
#endif
#ifdef GL_RETURN
  rb_define_const (rbclt_c_cogl, "RETURN",
                   INT2FIX (CGL_RETURN));
#endif
#ifdef GL_RGB
  rb_define_const (rbclt_c_cogl, "RGB",
                   INT2FIX (CGL_RGB));
#endif
#ifdef GL_RGBA
  rb_define_const (rbclt_c_cogl, "RGBA",
                   INT2FIX (CGL_RGBA));
#endif
#ifdef GL_RGBA_MODE
  rb_define_const (rbclt_c_cogl, "RGBA_MODE",
                   INT2FIX (CGL_RGBA_MODE));
#endif
#ifdef GL_RGB_SCALE
  rb_define_const (rbclt_c_cogl, "RGB_SCALE",
                   INT2FIX (CGL_RGB_SCALE));
#endif
#ifdef GL_RIGHT
  rb_define_const (rbclt_c_cogl, "RIGHT",
                   INT2FIX (CGL_RIGHT));
#endif
#ifdef GL_S
  rb_define_const (rbclt_c_cogl, "S",
                   INT2FIX (CGL_S));
#endif
#ifdef GL_SAMPLES
  rb_define_const (rbclt_c_cogl, "SAMPLES",
                   INT2FIX (CGL_SAMPLES));
#endif
#ifdef GL_SAMPLE_ALPHA_TO_COVERAGE
  rb_define_const (rbclt_c_cogl, "SAMPLE_ALPHA_TO_COVERAGE",
                   INT2FIX (CGL_SAMPLE_ALPHA_TO_COVERAGE));
#endif
#ifdef GL_SAMPLE_ALPHA_TO_ONE
  rb_define_const (rbclt_c_cogl, "SAMPLE_ALPHA_TO_ONE",
                   INT2FIX (CGL_SAMPLE_ALPHA_TO_ONE));
#endif
#ifdef GL_SAMPLE_BUFFERS
  rb_define_const (rbclt_c_cogl, "SAMPLE_BUFFERS",
                   INT2FIX (CGL_SAMPLE_BUFFERS));
#endif
#ifdef GL_SAMPLE_COVERAGE
  rb_define_const (rbclt_c_cogl, "SAMPLE_COVERAGE",
                   INT2FIX (CGL_SAMPLE_COVERAGE));
#endif
#ifdef GL_SAMPLE_COVERAGE_INVERT
  rb_define_const (rbclt_c_cogl, "SAMPLE_COVERAGE_INVERT",
                   INT2FIX (CGL_SAMPLE_COVERAGE_INVERT));
#endif
#ifdef GL_SAMPLE_COVERAGE_VALUE
  rb_define_const (rbclt_c_cogl, "SAMPLE_COVERAGE_VALUE",
                   INT2FIX (CGL_SAMPLE_COVERAGE_VALUE));
#endif
#ifdef GL_SCISSOR_BIT
  rb_define_const (rbclt_c_cogl, "SCISSOR_BIT",
                   INT2FIX (CGL_SCISSOR_BIT));
#endif
#ifdef GL_SCISSOR_BOX
  rb_define_const (rbclt_c_cogl, "SCISSOR_BOX",
                   INT2FIX (CGL_SCISSOR_BOX));
#endif
#ifdef GL_SCISSOR_TEST
  rb_define_const (rbclt_c_cogl, "SCISSOR_TEST",
                   INT2FIX (CGL_SCISSOR_TEST));
#endif
#ifdef GL_SELECT
  rb_define_const (rbclt_c_cogl, "SELECT",
                   INT2FIX (CGL_SELECT));
#endif
#ifdef GL_SELECTION_BUFFER_POINTER
  rb_define_const (rbclt_c_cogl, "SELECTION_BUFFER_POINTER",
                   INT2FIX (CGL_SELECTION_BUFFER_POINTER));
#endif
#ifdef GL_SELECTION_BUFFER_SIZE
  rb_define_const (rbclt_c_cogl, "SELECTION_BUFFER_SIZE",
                   INT2FIX (CGL_SELECTION_BUFFER_SIZE));
#endif
#ifdef GL_SEPARATE_SPECULAR_COLOR
  rb_define_const (rbclt_c_cogl, "SEPARATE_SPECULAR_COLOR",
                   INT2FIX (CGL_SEPARATE_SPECULAR_COLOR));
#endif
#ifdef GL_SET
  rb_define_const (rbclt_c_cogl, "SET",
                   INT2FIX (CGL_SET));
#endif
#ifdef GL_SHADE_MODEL
  rb_define_const (rbclt_c_cogl, "SHADE_MODEL",
                   INT2FIX (CGL_SHADE_MODEL));
#endif
#ifdef GL_SHININESS
  rb_define_const (rbclt_c_cogl, "SHININESS",
                   INT2FIX (CGL_SHININESS));
#endif
#ifdef GL_SHORT
  rb_define_const (rbclt_c_cogl, "SHORT",
                   INT2FIX (CGL_SHORT));
#endif
#ifdef GL_SINGLE_COLOR
  rb_define_const (rbclt_c_cogl, "SINGLE_COLOR",
                   INT2FIX (CGL_SINGLE_COLOR));
#endif
#ifdef GL_SLUMINANCE_ALPHA_EXT
  rb_define_const (rbclt_c_cogl, "SLUMINANCE_ALPHA_EXT",
                   INT2FIX (CGL_SLUMINANCE_ALPHA_EXT));
#endif
#ifdef GL_SLUMINANCE_EXT
  rb_define_const (rbclt_c_cogl, "SLUMINANCE_EXT",
                   INT2FIX (CGL_SLUMINANCE_EXT));
#endif
#ifdef GL_SMOOTH
  rb_define_const (rbclt_c_cogl, "SMOOTH",
                   INT2FIX (CGL_SMOOTH));
#endif
#ifdef GL_SMOOTH_LINE_WIDTH_GRANULARITY
  rb_define_const (rbclt_c_cogl, "SMOOTH_LINE_WIDTH_GRANULARITY",
                   INT2FIX (CGL_SMOOTH_LINE_WIDTH_GRANULARITY));
#endif
#ifdef GL_SMOOTH_LINE_WIDTH_RANGE
  rb_define_const (rbclt_c_cogl, "SMOOTH_LINE_WIDTH_RANGE",
                   INT2FIX (CGL_SMOOTH_LINE_WIDTH_RANGE));
#endif
#ifdef GL_SMOOTH_POINT_SIZE_GRANULARITY
  rb_define_const (rbclt_c_cogl, "SMOOTH_POINT_SIZE_GRANULARITY",
                   INT2FIX (CGL_SMOOTH_POINT_SIZE_GRANULARITY));
#endif
#ifdef GL_SMOOTH_POINT_SIZE_RANGE
  rb_define_const (rbclt_c_cogl, "SMOOTH_POINT_SIZE_RANGE",
                   INT2FIX (CGL_SMOOTH_POINT_SIZE_RANGE));
#endif
#ifdef GL_SPECULAR
  rb_define_const (rbclt_c_cogl, "SPECULAR",
                   INT2FIX (CGL_SPECULAR));
#endif
#ifdef GL_SPHERE_MAP
  rb_define_const (rbclt_c_cogl, "SPHERE_MAP",
                   INT2FIX (CGL_SPHERE_MAP));
#endif
#ifdef GL_SPOT_CUTOFF
  rb_define_const (rbclt_c_cogl, "SPOT_CUTOFF",
                   INT2FIX (CGL_SPOT_CUTOFF));
#endif
#ifdef GL_SPOT_DIRECTION
  rb_define_const (rbclt_c_cogl, "SPOT_DIRECTION",
                   INT2FIX (CGL_SPOT_DIRECTION));
#endif
#ifdef GL_SPOT_EXPONENT
  rb_define_const (rbclt_c_cogl, "SPOT_EXPONENT",
                   INT2FIX (CGL_SPOT_EXPONENT));
#endif
#ifdef GL_SRC_ALPHA
  rb_define_const (rbclt_c_cogl, "SRC_ALPHA",
                   INT2FIX (CGL_SRC_ALPHA));
#endif
#ifdef GL_SRC_ALPHA_SATURATE
  rb_define_const (rbclt_c_cogl, "SRC_ALPHA_SATURATE",
                   INT2FIX (CGL_SRC_ALPHA_SATURATE));
#endif
#ifdef GL_SRC_COLOR
  rb_define_const (rbclt_c_cogl, "SRC_COLOR",
                   INT2FIX (CGL_SRC_COLOR));
#endif
#ifdef GL_SRGB_ALPHA_EXT
  rb_define_const (rbclt_c_cogl, "SRGB_ALPHA_EXT",
                   INT2FIX (CGL_SRGB_ALPHA_EXT));
#endif
#ifdef GL_SRGB_EXT
  rb_define_const (rbclt_c_cogl, "SRGB_EXT",
                   INT2FIX (CGL_SRGB_EXT));
#endif
#ifdef GL_STACK_OVERFLOW
  rb_define_const (rbclt_c_cogl, "STACK_OVERFLOW",
                   INT2FIX (CGL_STACK_OVERFLOW));
#endif
#ifdef GL_STACK_UNDERFLOW
  rb_define_const (rbclt_c_cogl, "STACK_UNDERFLOW",
                   INT2FIX (CGL_STACK_UNDERFLOW));
#endif
#ifdef GL_STENCIL
  rb_define_const (rbclt_c_cogl, "STENCIL",
                   INT2FIX (CGL_STENCIL));
#endif
#ifdef GL_STENCIL_BITS
  rb_define_const (rbclt_c_cogl, "STENCIL_BITS",
                   INT2FIX (CGL_STENCIL_BITS));
#endif
#ifdef GL_STENCIL_BUFFER_BIT
  rb_define_const (rbclt_c_cogl, "STENCIL_BUFFER_BIT",
                   INT2FIX (CGL_STENCIL_BUFFER_BIT));
#endif
#ifdef GL_STENCIL_CLEAR_VALUE
  rb_define_const (rbclt_c_cogl, "STENCIL_CLEAR_VALUE",
                   INT2FIX (CGL_STENCIL_CLEAR_VALUE));
#endif
#ifdef GL_STENCIL_FAIL
  rb_define_const (rbclt_c_cogl, "STENCIL_FAIL",
                   INT2FIX (CGL_STENCIL_FAIL));
#endif
#ifdef GL_STENCIL_FUNC
  rb_define_const (rbclt_c_cogl, "STENCIL_FUNC",
                   INT2FIX (CGL_STENCIL_FUNC));
#endif
#ifdef GL_STENCIL_INDEX
  rb_define_const (rbclt_c_cogl, "STENCIL_INDEX",
                   INT2FIX (CGL_STENCIL_INDEX));
#endif
#ifdef GL_STENCIL_PASS_DEPTH_FAIL
  rb_define_const (rbclt_c_cogl, "STENCIL_PASS_DEPTH_FAIL",
                   INT2FIX (CGL_STENCIL_PASS_DEPTH_FAIL));
#endif
#ifdef GL_STENCIL_PASS_DEPTH_PASS
  rb_define_const (rbclt_c_cogl, "STENCIL_PASS_DEPTH_PASS",
                   INT2FIX (CGL_STENCIL_PASS_DEPTH_PASS));
#endif
#ifdef GL_STENCIL_REF
  rb_define_const (rbclt_c_cogl, "STENCIL_REF",
                   INT2FIX (CGL_STENCIL_REF));
#endif
#ifdef GL_STENCIL_TEST
  rb_define_const (rbclt_c_cogl, "STENCIL_TEST",
                   INT2FIX (CGL_STENCIL_TEST));
#endif
#ifdef GL_STENCIL_VALUE_MASK
  rb_define_const (rbclt_c_cogl, "STENCIL_VALUE_MASK",
                   INT2FIX (CGL_STENCIL_VALUE_MASK));
#endif
#ifdef GL_STENCIL_WRITEMASK
  rb_define_const (rbclt_c_cogl, "STENCIL_WRITEMASK",
                   INT2FIX (CGL_STENCIL_WRITEMASK));
#endif
#ifdef GL_STEREO
  rb_define_const (rbclt_c_cogl, "STEREO",
                   INT2FIX (CGL_STEREO));
#endif
#ifdef GL_SUBPIXEL_BITS
  rb_define_const (rbclt_c_cogl, "SUBPIXEL_BITS",
                   INT2FIX (CGL_SUBPIXEL_BITS));
#endif
#ifdef GL_SUBTRACT
  rb_define_const (rbclt_c_cogl, "SUBTRACT",
                   INT2FIX (CGL_SUBTRACT));
#endif
#ifdef GL_T
  rb_define_const (rbclt_c_cogl, "T",
                   INT2FIX (CGL_T));
#endif
#ifdef GL_TABLE_TOO_LARGE
  rb_define_const (rbclt_c_cogl, "TABLE_TOO_LARGE",
                   INT2FIX (CGL_TABLE_TOO_LARGE));
#endif
#ifdef GL_TEXTURE
  rb_define_const (rbclt_c_cogl, "TEXTURE",
                   INT2FIX (CGL_TEXTURE));
#endif
#ifdef GL_TEXTURE_2D
  rb_define_const (rbclt_c_cogl, "TEXTURE_2D",
                   INT2FIX (CGL_TEXTURE_2D));
#endif
#ifdef GL_TEXTURE_ALPHA_SIZE
  rb_define_const (rbclt_c_cogl, "TEXTURE_ALPHA_SIZE",
                   INT2FIX (CGL_TEXTURE_ALPHA_SIZE));
#endif
#ifdef GL_TEXTURE_BASE_LEVEL
  rb_define_const (rbclt_c_cogl, "TEXTURE_BASE_LEVEL",
                   INT2FIX (CGL_TEXTURE_BASE_LEVEL));
#endif
#ifdef GL_TEXTURE_BINDING_CUBE_MAP
  rb_define_const (rbclt_c_cogl, "TEXTURE_BINDING_CUBE_MAP",
                   INT2FIX (CGL_TEXTURE_BINDING_CUBE_MAP));
#endif
#ifdef GL_TEXTURE_BIT
  rb_define_const (rbclt_c_cogl, "TEXTURE_BIT",
                   INT2FIX (CGL_TEXTURE_BIT));
#endif
#ifdef GL_TEXTURE_BLUE_SIZE
  rb_define_const (rbclt_c_cogl, "TEXTURE_BLUE_SIZE",
                   INT2FIX (CGL_TEXTURE_BLUE_SIZE));
#endif
#ifdef GL_TEXTURE_BORDER
  rb_define_const (rbclt_c_cogl, "TEXTURE_BORDER",
                   INT2FIX (CGL_TEXTURE_BORDER));
#endif
#ifdef GL_TEXTURE_BORDER_COLOR
  rb_define_const (rbclt_c_cogl, "TEXTURE_BORDER_COLOR",
                   INT2FIX (CGL_TEXTURE_BORDER_COLOR));
#endif
#ifdef GL_TEXTURE_COMPONENTS
  rb_define_const (rbclt_c_cogl, "TEXTURE_COMPONENTS",
                   INT2FIX (CGL_TEXTURE_COMPONENTS));
#endif
#ifdef GL_TEXTURE_COMPRESSED
  rb_define_const (rbclt_c_cogl, "TEXTURE_COMPRESSED",
                   INT2FIX (CGL_TEXTURE_COMPRESSED));
#endif
#ifdef GL_TEXTURE_COMPRESSED_IMAGE_SIZE
  rb_define_const (rbclt_c_cogl, "TEXTURE_COMPRESSED_IMAGE_SIZE",
                   INT2FIX (CGL_TEXTURE_COMPRESSED_IMAGE_SIZE));
#endif
#ifdef GL_TEXTURE_COMPRESSION_HINT
  rb_define_const (rbclt_c_cogl, "TEXTURE_COMPRESSION_HINT",
                   INT2FIX (CGL_TEXTURE_COMPRESSION_HINT));
#endif
#ifdef GL_TEXTURE_COORD_ARRAY
  rb_define_const (rbclt_c_cogl, "TEXTURE_COORD_ARRAY",
                   INT2FIX (CGL_TEXTURE_COORD_ARRAY));
#endif
#ifdef GL_TEXTURE_COORD_ARRAY_POINTER
  rb_define_const (rbclt_c_cogl, "TEXTURE_COORD_ARRAY_POINTER",
                   INT2FIX (CGL_TEXTURE_COORD_ARRAY_POINTER));
#endif
#ifdef GL_TEXTURE_COORD_ARRAY_SIZE
  rb_define_const (rbclt_c_cogl, "TEXTURE_COORD_ARRAY_SIZE",
                   INT2FIX (CGL_TEXTURE_COORD_ARRAY_SIZE));
#endif
#ifdef GL_TEXTURE_COORD_ARRAY_STRIDE
  rb_define_const (rbclt_c_cogl, "TEXTURE_COORD_ARRAY_STRIDE",
                   INT2FIX (CGL_TEXTURE_COORD_ARRAY_STRIDE));
#endif
#ifdef GL_TEXTURE_COORD_ARRAY_TYPE
  rb_define_const (rbclt_c_cogl, "TEXTURE_COORD_ARRAY_TYPE",
                   INT2FIX (CGL_TEXTURE_COORD_ARRAY_TYPE));
#endif
#ifdef GL_TEXTURE_CUBE_MAP
  rb_define_const (rbclt_c_cogl, "TEXTURE_CUBE_MAP",
                   INT2FIX (CGL_TEXTURE_CUBE_MAP));
#endif
#ifdef GL_TEXTURE_CUBE_MAP_NEGATIVE_X
  rb_define_const (rbclt_c_cogl, "TEXTURE_CUBE_MAP_NEGATIVE_X",
                   INT2FIX (CGL_TEXTURE_CUBE_MAP_NEGATIVE_X));
#endif
#ifdef GL_TEXTURE_CUBE_MAP_NEGATIVE_Y
  rb_define_const (rbclt_c_cogl, "TEXTURE_CUBE_MAP_NEGATIVE_Y",
                   INT2FIX (CGL_TEXTURE_CUBE_MAP_NEGATIVE_Y));
#endif
#ifdef GL_TEXTURE_CUBE_MAP_NEGATIVE_Z
  rb_define_const (rbclt_c_cogl, "TEXTURE_CUBE_MAP_NEGATIVE_Z",
                   INT2FIX (CGL_TEXTURE_CUBE_MAP_NEGATIVE_Z));
#endif
#ifdef GL_TEXTURE_CUBE_MAP_POSITIVE_X
  rb_define_const (rbclt_c_cogl, "TEXTURE_CUBE_MAP_POSITIVE_X",
                   INT2FIX (CGL_TEXTURE_CUBE_MAP_POSITIVE_X));
#endif
#ifdef GL_TEXTURE_CUBE_MAP_POSITIVE_Y
  rb_define_const (rbclt_c_cogl, "TEXTURE_CUBE_MAP_POSITIVE_Y",
                   INT2FIX (CGL_TEXTURE_CUBE_MAP_POSITIVE_Y));
#endif
#ifdef GL_TEXTURE_CUBE_MAP_POSITIVE_Z
  rb_define_const (rbclt_c_cogl, "TEXTURE_CUBE_MAP_POSITIVE_Z",
                   INT2FIX (CGL_TEXTURE_CUBE_MAP_POSITIVE_Z));
#endif
#ifdef GL_TEXTURE_DEPTH
  rb_define_const (rbclt_c_cogl, "TEXTURE_DEPTH",
                   INT2FIX (CGL_TEXTURE_DEPTH));
#endif
#ifdef GL_TEXTURE_ENV
  rb_define_const (rbclt_c_cogl, "TEXTURE_ENV",
                   INT2FIX (CGL_TEXTURE_ENV));
#endif
#ifdef GL_TEXTURE_ENV_COLOR
  rb_define_const (rbclt_c_cogl, "TEXTURE_ENV_COLOR",
                   INT2FIX (CGL_TEXTURE_ENV_COLOR));
#endif
#ifdef GL_TEXTURE_ENV_MODE
  rb_define_const (rbclt_c_cogl, "TEXTURE_ENV_MODE",
                   INT2FIX (CGL_TEXTURE_ENV_MODE));
#endif
#ifdef GL_TEXTURE_GEN_MODE
  rb_define_const (rbclt_c_cogl, "TEXTURE_GEN_MODE",
                   INT2FIX (CGL_TEXTURE_GEN_MODE));
#endif
#ifdef GL_TEXTURE_GEN_Q
  rb_define_const (rbclt_c_cogl, "TEXTURE_GEN_Q",
                   INT2FIX (CGL_TEXTURE_GEN_Q));
#endif
#ifdef GL_TEXTURE_GEN_R
  rb_define_const (rbclt_c_cogl, "TEXTURE_GEN_R",
                   INT2FIX (CGL_TEXTURE_GEN_R));
#endif
#ifdef GL_TEXTURE_GEN_S
  rb_define_const (rbclt_c_cogl, "TEXTURE_GEN_S",
                   INT2FIX (CGL_TEXTURE_GEN_S));
#endif
#ifdef GL_TEXTURE_GEN_T
  rb_define_const (rbclt_c_cogl, "TEXTURE_GEN_T",
                   INT2FIX (CGL_TEXTURE_GEN_T));
#endif
#ifdef GL_TEXTURE_GREEN_SIZE
  rb_define_const (rbclt_c_cogl, "TEXTURE_GREEN_SIZE",
                   INT2FIX (CGL_TEXTURE_GREEN_SIZE));
#endif
#ifdef GL_TEXTURE_HEIGHT
  rb_define_const (rbclt_c_cogl, "TEXTURE_HEIGHT",
                   INT2FIX (CGL_TEXTURE_HEIGHT));
#endif
#ifdef GL_TEXTURE_INTENSITY_SIZE
  rb_define_const (rbclt_c_cogl, "TEXTURE_INTENSITY_SIZE",
                   INT2FIX (CGL_TEXTURE_INTENSITY_SIZE));
#endif
#ifdef GL_TEXTURE_INTERNAL_FORMAT
  rb_define_const (rbclt_c_cogl, "TEXTURE_INTERNAL_FORMAT",
                   INT2FIX (CGL_TEXTURE_INTERNAL_FORMAT));
#endif
#ifdef GL_TEXTURE_LUMINANCE_SIZE
  rb_define_const (rbclt_c_cogl, "TEXTURE_LUMINANCE_SIZE",
                   INT2FIX (CGL_TEXTURE_LUMINANCE_SIZE));
#endif
#ifdef GL_TEXTURE_MAG_FILTER
  rb_define_const (rbclt_c_cogl, "TEXTURE_MAG_FILTER",
                   INT2FIX (CGL_TEXTURE_MAG_FILTER));
#endif
#ifdef GL_TEXTURE_MATRIX
  rb_define_const (rbclt_c_cogl, "TEXTURE_MATRIX",
                   INT2FIX (CGL_TEXTURE_MATRIX));
#endif
#ifdef GL_TEXTURE_MAX_LEVEL
  rb_define_const (rbclt_c_cogl, "TEXTURE_MAX_LEVEL",
                   INT2FIX (CGL_TEXTURE_MAX_LEVEL));
#endif
#ifdef GL_TEXTURE_MAX_LOD
  rb_define_const (rbclt_c_cogl, "TEXTURE_MAX_LOD",
                   INT2FIX (CGL_TEXTURE_MAX_LOD));
#endif
#ifdef GL_TEXTURE_MIN_FILTER
  rb_define_const (rbclt_c_cogl, "TEXTURE_MIN_FILTER",
                   INT2FIX (CGL_TEXTURE_MIN_FILTER));
#endif
#ifdef GL_TEXTURE_MIN_LOD
  rb_define_const (rbclt_c_cogl, "TEXTURE_MIN_LOD",
                   INT2FIX (CGL_TEXTURE_MIN_LOD));
#endif
#ifdef GL_TEXTURE_PRIORITY
  rb_define_const (rbclt_c_cogl, "TEXTURE_PRIORITY",
                   INT2FIX (CGL_TEXTURE_PRIORITY));
#endif
#ifdef GL_TEXTURE_RECTANGLE_ARB
  rb_define_const (rbclt_c_cogl, "TEXTURE_RECTANGLE_ARB",
                   INT2FIX (CGL_TEXTURE_RECTANGLE_ARB));
#endif
#ifdef GL_TEXTURE_RED_SIZE
  rb_define_const (rbclt_c_cogl, "TEXTURE_RED_SIZE",
                   INT2FIX (CGL_TEXTURE_RED_SIZE));
#endif
#ifdef GL_TEXTURE_RESIDENT
  rb_define_const (rbclt_c_cogl, "TEXTURE_RESIDENT",
                   INT2FIX (CGL_TEXTURE_RESIDENT));
#endif
#ifdef GL_TEXTURE_STACK_DEPTH
  rb_define_const (rbclt_c_cogl, "TEXTURE_STACK_DEPTH",
                   INT2FIX (CGL_TEXTURE_STACK_DEPTH));
#endif
#ifdef GL_TEXTURE_STENCIL_SIZE_EXT
  rb_define_const (rbclt_c_cogl, "TEXTURE_STENCIL_SIZE_EXT",
                   INT2FIX (CGL_TEXTURE_STENCIL_SIZE_EXT));
#endif
#ifdef GL_TEXTURE_WIDTH
  rb_define_const (rbclt_c_cogl, "TEXTURE_WIDTH",
                   INT2FIX (CGL_TEXTURE_WIDTH));
#endif
#ifdef GL_TEXTURE_WRAP_R
  rb_define_const (rbclt_c_cogl, "TEXTURE_WRAP_R",
                   INT2FIX (CGL_TEXTURE_WRAP_R));
#endif
#ifdef GL_TEXTURE_WRAP_S
  rb_define_const (rbclt_c_cogl, "TEXTURE_WRAP_S",
                   INT2FIX (CGL_TEXTURE_WRAP_S));
#endif
#ifdef GL_TEXTURE_WRAP_T
  rb_define_const (rbclt_c_cogl, "TEXTURE_WRAP_T",
                   INT2FIX (CGL_TEXTURE_WRAP_T));
#endif
#ifdef GL_TIME_ELAPSED_EXT
  rb_define_const (rbclt_c_cogl, "TIME_ELAPSED_EXT",
                   INT2FIX (CGL_TIME_ELAPSED_EXT));
#endif
#ifdef GL_TRACE_ALL_BITS_MESA
  rb_define_const (rbclt_c_cogl, "TRACE_ALL_BITS_MESA",
                   INT2FIX (CGL_TRACE_ALL_BITS_MESA));
#endif
#ifdef GL_TRACE_ARRAYS_BIT_MESA
  rb_define_const (rbclt_c_cogl, "TRACE_ARRAYS_BIT_MESA",
                   INT2FIX (CGL_TRACE_ARRAYS_BIT_MESA));
#endif
#ifdef GL_TRACE_ERRORS_BIT_MESA
  rb_define_const (rbclt_c_cogl, "TRACE_ERRORS_BIT_MESA",
                   INT2FIX (CGL_TRACE_ERRORS_BIT_MESA));
#endif
#ifdef GL_TRACE_MASK_MESA
  rb_define_const (rbclt_c_cogl, "TRACE_MASK_MESA",
                   INT2FIX (CGL_TRACE_MASK_MESA));
#endif
#ifdef GL_TRACE_NAME_MESA
  rb_define_const (rbclt_c_cogl, "TRACE_NAME_MESA",
                   INT2FIX (CGL_TRACE_NAME_MESA));
#endif
#ifdef GL_TRACE_OPERATIONS_BIT_MESA
  rb_define_const (rbclt_c_cogl, "TRACE_OPERATIONS_BIT_MESA",
                   INT2FIX (CGL_TRACE_OPERATIONS_BIT_MESA));
#endif
#ifdef GL_TRACE_PIXELS_BIT_MESA
  rb_define_const (rbclt_c_cogl, "TRACE_PIXELS_BIT_MESA",
                   INT2FIX (CGL_TRACE_PIXELS_BIT_MESA));
#endif
#ifdef GL_TRACE_PRIMITIVES_BIT_MESA
  rb_define_const (rbclt_c_cogl, "TRACE_PRIMITIVES_BIT_MESA",
                   INT2FIX (CGL_TRACE_PRIMITIVES_BIT_MESA));
#endif
#ifdef GL_TRACE_TEXTURES_BIT_MESA
  rb_define_const (rbclt_c_cogl, "TRACE_TEXTURES_BIT_MESA",
                   INT2FIX (CGL_TRACE_TEXTURES_BIT_MESA));
#endif
#ifdef GL_TRANSFORM_BIT
  rb_define_const (rbclt_c_cogl, "TRANSFORM_BIT",
                   INT2FIX (CGL_TRANSFORM_BIT));
#endif
#ifdef GL_TRANSPOSE_COLOR_MATRIX
  rb_define_const (rbclt_c_cogl, "TRANSPOSE_COLOR_MATRIX",
                   INT2FIX (CGL_TRANSPOSE_COLOR_MATRIX));
#endif
#ifdef GL_TRANSPOSE_MODELVIEW_MATRIX
  rb_define_const (rbclt_c_cogl, "TRANSPOSE_MODELVIEW_MATRIX",
                   INT2FIX (CGL_TRANSPOSE_MODELVIEW_MATRIX));
#endif
#ifdef GL_TRANSPOSE_PROJECTION_MATRIX
  rb_define_const (rbclt_c_cogl, "TRANSPOSE_PROJECTION_MATRIX",
                   INT2FIX (CGL_TRANSPOSE_PROJECTION_MATRIX));
#endif
#ifdef GL_TRANSPOSE_TEXTURE_MATRIX
  rb_define_const (rbclt_c_cogl, "TRANSPOSE_TEXTURE_MATRIX",
                   INT2FIX (CGL_TRANSPOSE_TEXTURE_MATRIX));
#endif
#ifdef GL_TRIANGLES
  rb_define_const (rbclt_c_cogl, "TRIANGLES",
                   INT2FIX (CGL_TRIANGLES));
#endif
#ifdef GL_TRIANGLE_FAN
  rb_define_const (rbclt_c_cogl, "TRIANGLE_FAN",
                   INT2FIX (CGL_TRIANGLE_FAN));
#endif
#ifdef GL_TRIANGLE_STRIP
  rb_define_const (rbclt_c_cogl, "TRIANGLE_STRIP",
                   INT2FIX (CGL_TRIANGLE_STRIP));
#endif
#ifdef GL_TRUE
  rb_define_const (rbclt_c_cogl, "TRUE",
                   INT2FIX (CGL_TRUE));
#endif
#ifdef GL_UNPACK_ALIGNMENT
  rb_define_const (rbclt_c_cogl, "UNPACK_ALIGNMENT",
                   INT2FIX (CGL_UNPACK_ALIGNMENT));
#endif
#ifdef GL_UNPACK_IMAGE_HEIGHT
  rb_define_const (rbclt_c_cogl, "UNPACK_IMAGE_HEIGHT",
                   INT2FIX (CGL_UNPACK_IMAGE_HEIGHT));
#endif
#ifdef GL_UNPACK_LSB_FIRST
  rb_define_const (rbclt_c_cogl, "UNPACK_LSB_FIRST",
                   INT2FIX (CGL_UNPACK_LSB_FIRST));
#endif
#ifdef GL_UNPACK_ROW_LENGTH
  rb_define_const (rbclt_c_cogl, "UNPACK_ROW_LENGTH",
                   INT2FIX (CGL_UNPACK_ROW_LENGTH));
#endif
#ifdef GL_UNPACK_SKIP_IMAGES
  rb_define_const (rbclt_c_cogl, "UNPACK_SKIP_IMAGES",
                   INT2FIX (CGL_UNPACK_SKIP_IMAGES));
#endif
#ifdef GL_UNPACK_SKIP_PIXELS
  rb_define_const (rbclt_c_cogl, "UNPACK_SKIP_PIXELS",
                   INT2FIX (CGL_UNPACK_SKIP_PIXELS));
#endif
#ifdef GL_UNPACK_SKIP_ROWS
  rb_define_const (rbclt_c_cogl, "UNPACK_SKIP_ROWS",
                   INT2FIX (CGL_UNPACK_SKIP_ROWS));
#endif
#ifdef GL_UNPACK_SWAP_BYTES
  rb_define_const (rbclt_c_cogl, "UNPACK_SWAP_BYTES",
                   INT2FIX (CGL_UNPACK_SWAP_BYTES));
#endif
#ifdef GL_UNSIGNED_BYTE
  rb_define_const (rbclt_c_cogl, "UNSIGNED_BYTE",
                   INT2FIX (CGL_UNSIGNED_BYTE));
#endif
#ifdef GL_UNSIGNED_INT
  rb_define_const (rbclt_c_cogl, "UNSIGNED_INT",
                   INT2FIX (CGL_UNSIGNED_INT));
#endif
#ifdef GL_UNSIGNED_INT_8_8_8_8_REV
  rb_define_const (rbclt_c_cogl, "UNSIGNED_INT_8_8_8_8_REV",
                   INT2FIX (CGL_UNSIGNED_INT_8_8_8_8_REV));
#endif
#ifdef GL_UNSIGNED_SHORT
  rb_define_const (rbclt_c_cogl, "UNSIGNED_SHORT",
                   INT2FIX (CGL_UNSIGNED_SHORT));
#endif
#ifdef GL_UNSIGNED_SHORT_8_8_MESA
  rb_define_const (rbclt_c_cogl, "UNSIGNED_SHORT_8_8_MESA",
                   INT2FIX (CGL_UNSIGNED_SHORT_8_8_MESA));
#endif
#ifdef GL_UNSIGNED_SHORT_8_8_REV_MESA
  rb_define_const (rbclt_c_cogl, "UNSIGNED_SHORT_8_8_REV_MESA",
                   INT2FIX (CGL_UNSIGNED_SHORT_8_8_REV_MESA));
#endif
#ifdef GL_VENDOR
  rb_define_const (rbclt_c_cogl, "VENDOR",
                   INT2FIX (CGL_VENDOR));
#endif
#ifdef GL_VERSION
  rb_define_const (rbclt_c_cogl, "VERSION",
                   INT2FIX (CGL_VERSION));
#endif
#ifdef GL_VERTEX_ARRAY
  rb_define_const (rbclt_c_cogl, "VERTEX_ARRAY",
                   INT2FIX (CGL_VERTEX_ARRAY));
#endif
#ifdef GL_VERTEX_ARRAY_POINTER
  rb_define_const (rbclt_c_cogl, "VERTEX_ARRAY_POINTER",
                   INT2FIX (CGL_VERTEX_ARRAY_POINTER));
#endif
#ifdef GL_VERTEX_ARRAY_SIZE
  rb_define_const (rbclt_c_cogl, "VERTEX_ARRAY_SIZE",
                   INT2FIX (CGL_VERTEX_ARRAY_SIZE));
#endif
#ifdef GL_VERTEX_ARRAY_STRIDE
  rb_define_const (rbclt_c_cogl, "VERTEX_ARRAY_STRIDE",
                   INT2FIX (CGL_VERTEX_ARRAY_STRIDE));
#endif
#ifdef GL_VERTEX_ARRAY_TYPE
  rb_define_const (rbclt_c_cogl, "VERTEX_ARRAY_TYPE",
                   INT2FIX (CGL_VERTEX_ARRAY_TYPE));
#endif
#ifdef GL_VERTEX_PROGRAM_CALLBACK_DATA_MESA
  rb_define_const (rbclt_c_cogl, "VERTEX_PROGRAM_CALLBACK_DATA_MESA",
                   INT2FIX (CGL_VERTEX_PROGRAM_CALLBACK_DATA_MESA));
#endif
#ifdef GL_VERTEX_PROGRAM_CALLBACK_FUNC_MESA
  rb_define_const (rbclt_c_cogl, "VERTEX_PROGRAM_CALLBACK_FUNC_MESA",
                   INT2FIX (CGL_VERTEX_PROGRAM_CALLBACK_FUNC_MESA));
#endif
#ifdef GL_VERTEX_PROGRAM_CALLBACK_MESA
  rb_define_const (rbclt_c_cogl, "VERTEX_PROGRAM_CALLBACK_MESA",
                   INT2FIX (CGL_VERTEX_PROGRAM_CALLBACK_MESA));
#endif
#ifdef GL_VERTEX_PROGRAM_POSITION_MESA
  rb_define_const (rbclt_c_cogl, "VERTEX_PROGRAM_POSITION_MESA",
                   INT2FIX (CGL_VERTEX_PROGRAM_POSITION_MESA));
#endif
#ifdef GL_VERTEX_SHADER_ARB
  rb_define_const (rbclt_c_cogl, "VERTEX_SHADER",
                   INT2FIX (CGL_VERTEX_SHADER));
#endif
#ifdef GL_VIEWPORT
  rb_define_const (rbclt_c_cogl, "VIEWPORT",
                   INT2FIX (CGL_VIEWPORT));
#endif
#ifdef GL_VIEWPORT_BIT
  rb_define_const (rbclt_c_cogl, "VIEWPORT_BIT",
                   INT2FIX (CGL_VIEWPORT_BIT));
#endif
#ifdef GL_XOR
  rb_define_const (rbclt_c_cogl, "XOR",
                   INT2FIX (CGL_XOR));
#endif
#ifdef GL_YCBCR_MESA
  rb_define_const (rbclt_c_cogl, "YCBCR_MESA",
                   INT2FIX (CGL_YCBCR_MESA));
#endif
#ifdef GL_ZERO
  rb_define_const (rbclt_c_cogl, "ZERO",
                   INT2FIX (CGL_ZERO));
#endif
#ifdef GL_ZOOM_X
  rb_define_const (rbclt_c_cogl, "ZOOM_X",
                   INT2FIX (CGL_ZOOM_X));
#endif
#ifdef GL_ZOOM_Y
  rb_define_const (rbclt_c_cogl, "ZOOM_Y",
                   INT2FIX (CGL_ZOOM_Y));
#endif
}
